(function(){
'use strict';
const W3=["ACE","ACT","ADD","AGE","AIM","AIR","ALL","AND","ANY","ARM","ART","ASK","BAD","BAG","BAR","BAT","BED","BEE","BET","BIG","BOG","BOW","BOX","BOY","BUG","BUS","BUY","CAB","CAN","CAP","CAR","CAT","COW","CRY","CUP","CUT","DAD","DAY","DIP","DOG","DRY","DUE","EAR","EAT","EGG","EGO","END","ERA","EYE","FAN","FAR","FAT","FEE","FEW","FIT","FIX","FLU","FLY","FOG","FOR","FOX","FUN","GAP","GAS","GET","GOD","GOT","GUM","GUN","GUY","GYM","HAD","HAM","HAS","HAT","HEN","HER","HIM","HIS","HIT","HOT","HOW","HUB","HUG","HUT","ICE","ILL","INK","INN","ITS","JAM","JAR","JAW","JET","JOB","JOG","JOY","KEY","KID","KIN","KIT","LAB","LAP","LAW","LAY","LEG","LET","LID","LIE","LIP","LOG","LOT","LOW","MAD","MAN","MAP","MAT","MAX","MAY","MEN","MOM","MUD","MUG","NET","NEW","NIL","NOD","NON","NOR","NOT","NOW","NUT","OAK","OAR","OAT","ODD","OFF","OIL","OLD","ONE","OPT","OUR","OUT","OWL","OWN","PAD","PAN","PAR","PAT","PAW","PAY","PEA","PEN","PET","PIE","PIG","PIN","PIT","POT","PRO","PUP","PUT","RAG","RAM","RAN","RAT","RAW","RED","RIB","RID","RIG","RIM","RIP","ROD","ROW","RUB","RUG","RUN","SAD","SAW","SAY","SEA","SEE","SET","SEW","SHE","SHY","SIN","SIP","SIR","SIT","SIX","SKI","SKY","SLY","SON","SPY","SUN","TAG","TAP","TAX","TEA","TEN","THE","TIE","TIN","TIP","TOE","TON","TOP","TOY","TUB","TWO","USE","VAN","VAT","VET","VIA","WAR","WAS","WAX","WAY","WEB","WED","WHO","WHY","WIN","YES","YET","YOU","ZIP","ZOO"];
const W4=["ABLE","ACID","ALSO","AREA","ARMY","ATOM","BABY","BACK","BALL","BAND","BANK","BARE","BASE","BATH","BEAN","BEAR","BEAT","BELL","BELT","BEST","BILL","BIRD","BITE","BLOW","BLUE","BOIL","BOLD","BOLT","BOMB","BOND","BONE","BOOK","BOOM","BOSS","BOWL","BULK","BULL","BUMP","BURN","BUSY","CAGE","CAKE","CALL","CALM","CAMP","CANT","CARD","CARE","CARS","CART","CASH","CAST","CAVE","CELL","CHAT","CHEF","CHIP","CITY","CLUB","COAT","CODE","COIN","COLD","COOK","COOL","COPY","CORE","COST","CRAB","CREW","CROP","CUBE","CUTE","DARK","DASH","DATE","DAWN","DEAD","DEAL","DEAR","DEBT","DECK","DEEP","DENY","DESK","DIET","DIRT","DISK","DOLL","DOOR","DRAW","DROP","DRUM","DUAL","DUCK","DUNE","DUST","DUTY","EACH","EARN","EAST","EASY","EDGE","EPIC","EVEN","EVER","EVIL","EXAM","EXIT","FACE","FACT","FAIR","FALL","FAME","FARM","FAST","FATE","FEAR","FILL","FILM","FIND","FINE","FIRE","FISH","FLAG","FLIP","FLOW","FOLD","FOND","FOOD","FOOT","FORK","FORM","FORT","FREE","FUEL","FULL","FUND","GAIN","GAME","GANG","GATE","GEAR","GENE","GIFT","GIRL","GLAD","GLOW","GOAL","GOLD","GOLF","GONE","GOOD","GRAB","GRAY","GRID","GROW","GULF","HACK","HAIR","HALF","HALL","HAND","HARD","HATE","HEAD","HEAL","HEAR","HEAT","HELD","HELL","HELP","HERE","HERO","HIGH","HILL","HINT","HOLD","HOLE","HOLY","HOME","HOOD","HOPE","HOST","HOUR","HUGE","HUNT","HURT","ICON","IDEA","IDLE","INTO","IRON","ITEM","JACK","JAIL","JAZZ","JOIN","JOKE","JUMP","JURY","JUST","KEEN","KEEP","KICK","KILL","KIND","KING","KISS","KNEE","KNEW","KNOW","LACK","LADY","LAKE","LAMP","LAND","LANE","LAST","LATE","LEAD","LEAF","LEFT","LEND","LESS","LIFE","LIFT","LIKE","LIME","LINE","LINK","LION","LIST","LIVE","LOAD","LOCK","LOGO","LONG","LOOK","LORD","LOSE","LOSS","LOST","LOUD","LOVE","LUCK","LUMP","MADE","MAIL","MAIN","MAKE","MALE","MALL","MANY","MARK","MASS","MATE","MAZE","MEAL","MEAN","MEAT","MEET","MELT","MENU","MILD","MILE","MILK","MIND","MINE","MINT","MISS","MODE","MOOD","MOON","MORE","MOST","MOVE","MUCH","MUST","MYTH","NAIL","NAME","NAVY","NEAT","NECK","NEED","NEST","NEWS","NEXT","NICE","NINE","NODE","NONE","NOSE","NOTE","ODDS","OKAY","ONCE","ONLY","OPEN","OVER","PACE","PACK","PAGE","PAID","PAIN","PAIR","PALE","PALM","PARK","PART","PASS","PAST","PATH","PEAK","PICK","PILE","PINE","PINK","PIPE","PLAN","PLAY","PLOT","PLUG","PLUS","POEM","POET","POLE","POLL","POND","POOL","POOR","PORK","PORT","POSE","POST","POUR","PRAY","PROP","PULL","PUMP","PURE","PUSH","QUIT","RACE","RAGE","RAID","RAIL","RAIN","RANK","RARE","RATE","READ","REAL","RENT","REST","RICE","RICH","RIDE","RING","RISE","RISK","ROAD","ROCK","ROLE","ROLL","ROOF","ROOM","ROOT","ROPE","ROSE","RUIN","RULE","RUSH","SAFE","SAID","SAIL","SAKE","SALE","SALT","SAME","SAND","SAVE","SEAL","SEAT","SEED","SEEK","SEEM","SELF","SELL","SEND","SENT","SHED","SHIP","SHOE","SHOP","SHOT","SHOW","SHUT","SICK","SIDE","SIGN","SILK","SING","SINK","SITE","SIZE","SKIN","SKIP","SLIM","SLIP","SLOT","SLOW","SNAP","SNOW","SOAP","SOFT","SOIL","SOLD","SOLE","SOME","SONG","SOON","SORT","SOUL","SOUP","SOUR","SPAN","SPIN","SPOT","STAR","STAY","STEM","STEP","STOP","SUCH","SUIT","SURE","SURF","SWAN","SWAP","SWIM","TAIL","TAKE","TALE","TALK","TALL","TANK","TAPE","TASK","TAXI","TEAM","TEAR","TELL","TEND","TENT","TERM","TEST","TEXT","THAT","THEM","THEN","THEY","THIN","THIS","TICK","TIDE","TIED","TILL","TIME","TINY","TIRE","TOLD","TOLL","TONE","TOOK","TOOL","TOPS","TORN","TOUR","TOWN","TRAP","TREE","TRIM","TRIP","TRUE","TUBE","TUNE","TURN","TWIN","TYPE","UGLY","UNDO","UNIT","UPON","URGE","USED","USER","VARY","VAST","VERY","VIEW","VINE","VOID","VOLT","VOTE","WADE","WAGE","WAIT","WAKE","WALK","WALL","WANT","WARD","WARM","WARN","WASH","WAVE","WEAK","WEAR","WEED","WEEK","WELL","WENT","WEST","WHAT","WHEN","WIDE","WIFE","WILD","WILL","WIND","WINE","WING","WIRE","WISE","WISH","WITH","WOKE","WOLF","WOOD","WOOL","WORD","WORK","WORM","WORN","WRAP","YARD","YEAR","YOUR","ZEAL","ZERO","ZONE","ZOOM"];
const W5=["ABOVE","ACTOR","ACUTE","ADAPT","ADMIT","ADOPT","ADULT","AFTER","AGENT","AGREE","ALARM","ALBUM","ALIVE","ALLOW","ALONE","ALONG","ALTER","ANGER","ANGLE","ANGRY","APART","APPLE","ASSET","AUDIT","AVOID","AWARD","AWARE","AWFUL","BASIC","BASIS","BEACH","BEGAN","BEGIN","BEGUN","BEING","BELOW","BENCH","BIRTH","BLACK","BLAME","BLIND","BLOCK","BLOOD","BOARD","BOOST","BOUND","BRAIN","BRAVE","BREAK","BREED","BRIEF","BROAD","BROWN","BUILD","BUYER","CABLE","CACHE","CANDY","CARRY","CATCH","CAUSE","CHAIN","CHAIR","CHARM","CHART","CHASE","CHEAP","CHECK","CHEST","CHIEF","CHILD","CHILL","CHUCK","CIGAR","CLAIM","CLASS","CLEAN","CLIMB","CLOCK","CLOSE","CLOUD","COACH","COAST","COLOR","CORAL","COUNT","COURT","COVER","CRANE","CRAZY","CREAM","CRIME","CROSS","CROWD","CROWN","CURVE","CYCLE","DAILY","DAIRY","DANCE","DEATH","DELAY","DEPTH","DEVIL","DIRTY","DIZZY","DOING","DONOR","DOUBT","DOZEN","DRAFT","DRAMA","DREAM","DRESS","DRIFT","DRILL","DRINK","DRIVE","DYING","EAGER","EAGLE","EARLY","EARTH","EIGHT","ELITE","EMBER","EMPTY","ENEMY","ENJOY","ENTER","ENTRY","EQUAL","ERROR","EVENT","EXACT","EXIST","EXTRA","FAINT","FAITH","FALSE","FAULT","FAVOR","FEAST","FIBER","FIELD","FIFTH","FIFTY","FIGHT","FINAL","FIRST","FIXED","FLAME","FLASH","FLEET","FLESH","FLOAT","FLOOD","FLOOR","FLORA","FLOUR","FLUID","FOCUS","FORCE","FORTE","FORTH","FORUM","FOUND","FRAME","FRANK","FRAUD","FRESH","FRONT","FROST","FRUIT","FUNNY","GHOST","GIANT","GIVEN","GLASS","GLOBE","GLORY","GOING","GRACE","GRADE","GRAND","GRANT","GRAPE","GRASP","GRASS","GREAT","GREEN","GRIND","GROSS","GROUP","GROWN","GUARD","GUESS","GUEST","GUIDE","HABIT","HAPPY","HARSH","HAVEN","HEART","HEAVY","HELLO","HENCE","HONEY","HORSE","HOTEL","HOUSE","HUMAN","IDEAL","IMAGE","INDEX","INNER","INPUT","ISSUE","IVORY","JEWEL","JOINT","JUDGE","JUICE","KNIFE","KNOCK","LABEL","LABOR","LARGE","LASER","LATIN","LAUGH","LAYER","LEARN","LEAST","LEAVE","LEGAL","LEMON","LEVEL","LIGHT","LIMIT","LINEN","LIVER","LOCAL","LOGIC","LOOSE","LOWER","LOYAL","LUCKY","LUNAR","LUNCH","MAGIC","MAJOR","MAKER","MANOR","MAPLE","MARCH","MARSH","MATCH","MAYOR","MEANT","MEDAL","MEDIA","MERIT","METAL","MIGHT","MINOR","MODEL","MONEY","MONTH","MORAL","MOTOR","MOUNT","MOUSE","MOUTH","MOVIE","MUSIC","NAKED","NAVAL","NERVE","NEVER","NEWLY","NIGHT","NOBLE","NOISE","NORTH","NOTED","NOVEL","NURSE","OCCUR","OCEAN","OFFER","OFTEN","ONION","ORBIT","ORDER","OTHER","OUGHT","OUNCE","OUTER","OXIDE","PAINT","PANEL","PANIC","PAPER","PARTY","PATCH","PEACE","PEACH","PEARL","PHASE","PIANO","PIECE","PILOT","PITCH","PIXEL","PLACE","PLAIN","PLANE","PLANT","PLATE","PLAZA","PLUMB","POINT","POLAR","POUND","POWER","PRESS","PRICE","PRIDE","PRIME","PRINT","PRIOR","PRIZE","PROOF","PROUD","PROVE","PULSE","QUEEN","QUEST","QUICK","QUIET","QUITE","RADAR","RADIO","RAISE","RANGE","RAPID","RATIO","REACH","REACT","READY","REALM","REBEL","REFER","REIGN","RELAX","RELAY","RETRO","RIDER","RIGHT","RIVER","ROAD","ROBOT","ROUGH","ROUND","ROUTE","ROYAL","RUGBY","RULER","RURAL","RUSH","SACRED","SAINT","SALAD","SCALE","SCENE","SCOPE","SCORE","SCRAP","SENSE","SERVE","SEVEN","SHADE","SHAKE","SHALL","SHAME","SHAPE","SHARE","SHARP","SHEEP","SHEET","SHELF","SHELL","SHIFT","SHINE","SHIRT","SHOCK","SHOOT","SHORT","SHOUT","SIGHT","SINCE","SIXTY","SKILL","SKIRT","SKULL","SLASH","SLAVE","SLEEP","SLICE","SLIDE","SMALL","SMART","SMELL","SMILE","SMOKE","SNAKE","SNEAK","SOLAR","SOLID","SOLVE","SORRY","SOUND","SOUTH","SPACE","SPARE","SPARK","SPEAK","SPEED","SPELL","SPEND","SPICE","SPILL","SPINE","SPITE","SPLIT","SPOKE","SPORT","SPRAY","STACK","STAFF","STAGE","STAIR","STAKE","STALE","STAND","STARK","START","STATE","STEAL","STEAM","STEEL","STEEP","STEER","STERN","STICK","STILL","STOCK","STONE","STORE","STORM","STORY","STOVE","STUFF","STYLE","SUGAR","SUITE","SUPER","SURGE","SWAMP","SWEAR","SWEAT","SWEEP","SWEET","SWIFT","SWING","SWORD","TABLE","TASTE","TAXES","TEACH","TEETH","TENTH","TERRY","TEXAS","THANK","THEFT","THEIR","THEME","THERE","THESE","THICK","THIEF","THING","THINK","THIRD","THORN","THOSE","THREE","THROW","TIGER","TIGHT","TITLE","TODAY","TOKEN","TOKIO","TOOTH","TOPIC","TOTAL","TOUCH","TOUGH","TOWER","TOXIC","TRACE","TRACK","TRACT","TRADE","TRAIL","TRAIN","TRAIT","TRASH","TREAT","TREND","TRIAL","TRIBE","TRICK","TROOP","TRUCK","TRULY","TRUST","TRUTH","TULIP","TWICE","TWIST","ULTRA","UNDER","UNION","UNITE","UNITY","UNTIL","UPPER","UPSET","URBAN","USUAL","UTTER","VALID","VALUE","VAULT","VIDEO","VIGOR","VIRUS","VISIT","VITAL","VIVID","VOCAL","VOICE","VOTER","WAGON","WATCH","WATER","WEARY","WEIGH","WHEAT","WHEEL","WHERE","WHICH","WHILE","WHITE","WHOLE","WHOSE","WIDELY","WITCH","WOMAN","WORLD","WORRY","WORSE","WORST","WORTH","WOULD","WOUND","WRATH","WRIST","WRITE","WRONG","YIELD","YOUNG","YOUTH","ZEBRA"];
const W6=["ABSORB","ACCEPT","ACCESS","ACTION","ACTIVE","ACTUAL","ADVICE","ADVISE","AFFORD","AGENCY","AGENDA","ALMOST","ALWAYS","AMOUNT","ANCHOR","ANIMAL","ANNUAL","ANSWER","ANYONE","ANYWAY","APPEAL","APPEAR","AROUND","ARRIVE","ARTIST","ASKING","ASSESS","ASSIGN","ASSIST","ASSUME","ATTACK","ATTEND","AUTHOR","AVENUE","BACKED","BAKING","BALLOT","BANKER","BARREL","BASKET","BATTLE","BEACON","BEATEN","BEAUTY","BECOME","BEFORE","BEHALF","BEHIND","BELIEF","BELONG","BEYOND","BISHOP","BLOCKS","BOARDS","BODIES","BORDER","BORROW","BOSSES","BOTTLE","BOTTOM","BOUGHT","BOUNCE","BRANCH","BRAZIL","BREATH","BRIDGE","BRIGHT","BROKEN","BROKER","BRONZE","BROTHER","BUCKET","BUDGET","BUFFER","BULLET","BURDEN","BUREAU","BURNER","BURTON","BUTTON","BUYERS","CALLER","CAMERA","CAMPUS","CANCEL","CANCER","CANDID","CANNOT","CANVAS","CARBON","CAREER","CAREFUL","CARING","CARTON","CASINO","CASTLE","CASUAL","CATCHY","CAUGHT","CAUSES","CENTER","CENTRE","CHANCE","CHANGE","CHARGE","CHIEFS","CHOCOLATE","CHOICE","CHOOSE","CHOSEN","CHURCH","CINEMA","CIPHER","CIRCLE","CIRCUS","CITIZEN","CLEVER","CLIENT","CLINIC","CLOSED","CLOSER","CLOSET","CLOTHS","CLUTCH","COFFEE","COLLAR","COLUMN","COMBAT","COMEDY","COMMIT","COMMON","COMPEL","COMPLY","CONVEY","CONVOY","COOKIE","COOLER","COPPER","CORNER","CORPUS","COTTON","COUPLE","COUPON","COURSE","COUSIN","COVERS","CREATE","CREDIT","CRISIS","CRITIC","CRUISE","CRYING","CUSTOM","CUTTER","DAMAGE","DANCER","DANGER","DARING","DAZZLE","DEADLY","DEBATE","DEBRIS","DECADE","DECIDE","DECLINE","DECODE","DECREE","DEFEAT","DEFEND","DEFICIT","DEGREE","DELAYED","DELETE","DEMAND","DENTIST","DEPART","DEPEND","DEPLOY","DEPUTY","DERIVE","DESERT","DESIGN","DESIRE","DETAIL","DETECT","DEVICE","DEVOTE","DIFFER","DIGEST","DINNER","DIRECT","DIVIDE","DOCTOR","DOLLAR","DOMAIN","DOUBLE","DOZENS","DRAGON","DRAWER","DRIVEN","DRIVER","DURING","EASILY","EATING","EFFECT","EFFORT","EIGHTH","EITHER","ELDEST","ELEVEN","EMERGE","EMPIRE","EMPLOY","ENABLE","ENERGY","ENGAGE","ENGINE","ENJOY","ENROLL","ENTIRE","ENTITY","ENVOY","ESCAPE","ESTATE","ESTIMATE","ETHICS","EXCEED","EXCEPT","EXCESS","EXPAND","EXPECT","EXPERT","EXPORT","EXPOSE","EXTEND","EXTENT","FABRIC","FACING","FACTOR","FAILED","FAIRLY","FALCON","FALLEN","FAMILY","FAMOUS","FATHER","FAULTY","FEARS","FEDERAL","FELLOW","FEMALE","FIERCE","FIFTHS","FIGURE","FILING","FILTER","FINISH","FINITE","FIRMLY","FISCAL","FITTED","FIXING","FLIGHT","FLOODS","FLORAL","FLOWER","FLYING","FOLKS","FOLLOW","FORCED","FORCES","FOREGO","FOREST","FORGET","FORMAL","FORMAT","FORMER","FOSSIL","FOSTER","FOUGHT","FOURTH","FRANCE","FRENCH","FRIDAY","FRIEND","FRIGHT","FRINGE","FROZEN","FULLY","FUNDING","FUTURE","GAINED","GALAXY","GARDEN","GATHER","GENDER","GENIUS","GENTLE","GERMAN","GHOSTS","GLOBAL","GLORIOUS","GOLDEN","GOSPEL","GROUND","GROWTH","GUILTY","GUITAR","HANDED","HANDLE","HAPPEN","HARBOR","HARDLY","HASHTAG","HEALTH","HEARTS","HEAVEN","HEAVILY","HEIGHT","HEROES","HIDDEN","HIGHER","HIGHLY","HOLDER","HOLLOW","HONEST","HONOUR","HOOKED","HOPING","HORROR","HORSES","HOSTEL","HOSTILE","HUGHES","HUMBLE","HUNTER","HURT","IMPACT","INJURY","INLAND","INMATE","INSERT","INSIDE","INTEND","INTENT","INVEST","ISLAND","ISSUES","ITSELF","JACKET","JERSEY","JOINED","JOSEPH","JUDGES","JULIAN","JUMPING","JUNGLE","JUNIOR","JURIS","JUROR","JUSTLY","KEEPER","KICKED","KILLED","KILLER","KINDLY","KNIGHT","KNIVES","KOREAN","LABELS","LABOR","LACKING","LADDER","LATELY","LATEST","LATINO","LAUNCH","LAWYER","LEADER","LEAGUE","LEAVES","LEGACY","LEGEND","LENTIL","LESSON","LETTER","LEVELS","LIABLE","LIBRAR","LIKE","LIKELY","LIMITS","LINEAR","LINKED","LIQUID","LISTEN","LITTLE","LIVING","LOCALS","LOCATE","LOGGED","LONDON","LONELY","LOSING","LOVERS","LOVING","LOWEST","LUXURY","MACRO","MAGNET","MAIDEN","MAINLY","MAKERS","MAKING","MANAGE","MANNER","MANUAL","MARBLE","MARGIN","MARINE","MARKER","MARKET","MARVEL","MASTER","MATRIX","MATTER","MATURE","MEADOW","MECHAN","MEDALS","MEDIUM","MEMBER","MEMORY","MENTAL","MERELY","MERGER","METHOD","MIDDLE","MIGHTY","MILLED","MINUTE","MIRROR","MISSED","MOBILE","MODALS","MODERN","MODEST","MODIFY","MODULE","MOMENT","MONACO","MONKEY","MORALS","MOSTLY","MOTHER","MOTION","MOTIVE","MOTORS","MOUNTS","MOVING","MURDER","MUSCLE","MUSEUM","MUTUAL","MYSELF","MYSTIC","NARROW","NATION","NATIVE","NATURE","NEARLY","NEEDED","NEEDLE","NELSON","NERVES","NESTED","NEVADA","NEWEST","NEWTON","NICELY","NINETY","NOBODY","NODULE","NORMAL","NOTICE","NOTION","NUMBER","NURSES","OBJECT","OBSERVE","OBTAIN","OCCUPY","OCCURS","OFFEND","OFFICE","OFFSET","ONLINE","OPENED","OPPOSE","OPTION","ORACLE","ORANGE","ORBITS","ORDERS","ORGANS","ORIGIN","OTHERS","OUTLET","OUTPUT","OUTSET","OXFORD","OYSTER","PACING","PACKED","PACKET","PALACE","PANELS","PARCEL","PARDON","PARENT","PARISH","PARKS","PAROLE","PARROT","PARTLY","PASSES","PASTOR","PATENT","PATROL","PATRON","PAYING","PEARLS","PEASANT","PEDAL","PENALTY","PENCIL","PEOPLE","PEPPER","PERIOD","PERMIT","PERSON","PHASES","PHONES","PHRASES","PICKED","PIECES","PILLOW","PILOTS","PISTOL","PLACED","PLACES","PLANES","PLANET","PLANTS","PLAQUE","PLATES","PLEASE","PLEDGE","PLENTY","PLUNGE","POCKET","POETRY","POISON","POLICE","POLICY","POLISH","POLITE","POUNDS","POWDER","POWERS","PRAISE","PRAYER","PREFER","PRETTY","PRICES","PRIEST","PRIMAL","PRISON","PRIZES","PROFIT","PROMPT","PROPER","PROVE","PROVED","PROXY","PUBLIC","PULLING","PULSES","PUNISH","PUPILS","PURELY","PURPLE","PURSUE","PUZZLE","QUARTZ","QUEENS","QUESTS","RACING","RADIUS","RANDOM","RANGES","RARELY","RATING","RATIOS","READER","REALLY","REASON","REBELS","RECALL","RECENT","RECIPE","RECORD","REDUCE","REFORM","REFUSE","REGARD","REGION","REJECT","RELATE","RELIED","RELIEF","REMAIN","REMEDY","REMIND","REMOVE","RENDER","REPEAT","REPLAY","REPORT","RESCUE","RESIGN","RESORT","RESULT","RETAIL","RETAIN","RETURN","REVEAL","REVIEW","REWARD","RHYTHM","RIBBON","RIDERS","RIDING","RIGHTLY","RISING","RITUAL","RIVERS","ROBUST","ROCKET","ROLLIN","ROMANS","ROSTER","ROTARY","ROUGHLY","ROUNDS","RUBBER","RULING","RUNNER","RUNWAY","RURAL","RUSSIAN","SACRED","SAFELY","SAFETY","SAILOR","SALARY","SALMON","SAMPLES","SANTA","SAVAGE","SAVING","SAYING","SCALES","SCARCE","SCENES","SCHEME","SCHOLAR","SCHOOL","SCREEN","SCRIPT","SEARCH","SEASON","SECOND","SECRET","SECTOR","SECURE","SEEING","SELECT","SELLER","SENATE","SENIOR","SENSES","SENSOR","SERIES","SERVER","SETTLE","SEVERE","SEWING","SEXUAL","SHADOW","SHAKEN","SHAKES","SHAPES","SHARES","SHARKS","SHARPLY","SHEETS","SHELLS","SHIELD","SHIFTS","SHINING","SHIRTS","SHOCKS","SHOOTS","SHORES","SHORTLY","SHORTS","SHOULD","SHOUTS","SHOWN","SHOWS","SHRINK","SIGHTS","SIGNAL","SIGNED","SILENT","SILVER","SIMILAR","SIMPLE","SIMPLY","SINGER","SINGLE","SISTER","SKETCH","SKILLS","SKINS","SKIRTS","SKYP","SLEDGE","SLEEPS","SLICES","SLIDES","SLIGHT","SLOWLY","SMELLS","SMILES","SMOKER","SMOOTH","SNACKS","SNAKES","SOCCER","SOCIAL","SOCKET","SODIUM","SOFTLY","SOLVED","SOMETHING","SOURCE","SOVIET","SPACES","SPARED","SPARKS","SPEAKS","SPEECH","SPEEDS","SPELLS","SPENDS","SPHERE","SPICES","SPIRIT","SPOKEN","SPORTS","SPREAD","SPRING","SQAURE","SQUARE","STABLE","STAGE","STAIRS","STAKES","STAMPS","STANCE","STANDS","STARES","STARTS","STATED","STATES","STATUS","STAYS","STEADY","STEALS","STEAM","STEMS","STEPS","STICKS","STINGS","STITCH","STOCKS","STOLEN","STONES","STORED","STORES","STORMS","STRAIN","STRAPS","STREAM","STREET","STRESS","STRICT","STRIKE","STRING","STRIPS","STRIVE","STRONG","STRUCK","STUDIED","STUDIO","STUFFS","STUPID","STURDY","STYLES","SUBMIT","SUBSET","SUBTLE","SUBURB","SUFFER","SUMMER","SUMMIT","SUNSET","SUPERB","SUPPLY","SURELY","SURVEY","SURVIVE","SUTTON","SWEARS","SWEATS","SWEDEN","SWEETS","SWELLS","SWITCH","SWORDS","SYMBOL","SYMPTOM","SYSTEM","TACKLE","TACTIC","TAILOR","TAKING","TALENT","TARGET","TASTES","TASTY","TAUGHT","TAVERNS","TAXING","TEACHER","TEAMS","TEARS","TEEING","TELLS","TEMPLE","TENANT","TENDER","TENNIS","TENSE","TENURE","TERROR","TESTING","TEXAN","THEMES","THEORY","THERAPY","THINGS","THINKS","THIRST","THIRTY","THOUGH","THOUGHT","THREAD","THREAT","THRIVE","THRONE","THROWN","TICKET","TICKETS","TIEING","TIGERS","TIMBER","TIMELY","TIMING","TISSUES","TITLES","TODAY","TOMATO","TONGUE","TONIGHT","TOPICS","TOWARD","TOXINS","TRACTS","TRADES","TRAGIC","TRAILS","TRAINS","TRAITS","TRAUMA","TRAVEL","TREATY","TRENDS","TRIBES","TRICKS","TRIES","TRIGGER","TRIVIA","TROOPS","TROPHY","TRUCKS","TRUSTS","TRUTHS","TRYING","TSETSE","TUITION","TUNING","TUNNEL","TURKEY","TURNED","TURTLE","TWELVE","TWENTY","TWICE","TWINS","TWISTS","TYPICAL","TYPING","UNABLE","UNCLE","UNFOLD","UNIQUE","UNITED","UNJUST","UNLESS","UNLIKE","UNLOCK","UNPAID","UNREST","UNSEEN","UNTOLD","UNUSUAL","UPBEAT","UPDATE","UPHOLD","UPRIGHT","UPSET","UPWARD","URGENT","USEFUL","USING","USUAL","UTMOST","VACANT","VACUUM","VALLEY","VALUES","VALVES","VANISH","VARIED","VARIES","VARYING","VASSAL","VAULTS","VECTOR","VEGGIE","VELVET","VENDOR","VERBAL","VERGE","VERIFY","VERSUS","VERTEX","VESSEL","VIABLE","VICTIM","VICTOR","VIDEOS","VIEWED","VIEWER","VIGOUR","VILLAGE","VIOLET","VIOLIN","VIRGIN","VIRTUE","VIRUS","VISION","VISITS","VISUAL","VOCAB","VOCALS","VOICES","VOLUME","VORTEX","VOTERS","VOTING","VOYAGE","WAGES","WAITED","WAITER","WAIVES","WALKING","WALNUT","WANDER","WANTED","WARILY","WARMTH","WARNED","WARREN","WASHED","WASHER","WASTED","WATCH","WATER","WEAKER","WEALTH","WEAPON","WEARER","WEAVER","WEAVING","WEBSIT","WEEKLY","WEIGHT","WELDED","WELDER","WELDING","WELFARE","WHOLLY","WICKED","WIDELY","WIDOW","WIDTH","WILDLY","WILLOW","WINDOW","WINNER","WINTER","WIRING","WISDOM","WISHED","WITCH","WITHAL","WIZARD","WONDER","WOODEN","WORKER","WORLD","WORRY","WORSE","WORST","WORTH","WRITER","WRITTEN","WRONG","YELLOW","YIELD","YOUTHS","ZENITH"];
const W7=["ABILITY","ACCOUNT","ADDRESS","ADVANCE","ALREADY","ANALYZE","ANOTHER","ANYBODY","ANYMORE","APOLOGY","APPAREL","ARTICLE","ATTEMPT","ATTRACT","AUCTION","AVERAGE","BALANCE","BATTERY","BECAUSE","BEDROOM","BELIEVE","BENEATH","BENEFIT","BESIDES","BETWEEN","BICYCLE","BILLION","BLANKET","BLOSSOM","BOILING","BROTHER","CABINET","CALIBER","CAPITAL","CAPTAIN","CAPTURE","CAREFUL","CARRIER","CEILING","CENTRAL","CENTURY","CERTAIN","CERTIFY","CHAMBER","CHANNEL","CHAPTER","CHARITY","CHARLIE","CHICKEN","CIRCUIT","CITIZEN","CLASSES","CLASSIC","CLIMATE","CLOTHES","COLLECT","COLLEGE","COMBINE","COMFORT","COMMAND","COMMENT","COMPANY","COMPARE","COMPASS","COMPLEX","CONCEPT","CONCERN","CONNECT","CONSIST","CONTACT","CONTAIN","CONTENT","CONTEST","CONTEXT","CONTROL","CORRECT","COUNCIL","COUNTRY","COURAGE","CRUCIAL","CRYSTAL","CULTURE","CURRENT","CUSHION","CUSTOMS","DANCING","DECADES","DECLINE","DEFAULT","DEFENSE","DEFICIT","DELIVER","DENSITY","DEPOSIT","DESCENT","DESERVE","DESKTOP","DESPAIR","DESTINY","DESTROY","DETAILS","DEVELOP","DIAMOND","DICTATE","DIGITAL","DILEMMA","DISEASE","DISPLAY","DISPUTE","DIVERSE","DIVIDED","DIVORCE","DOLPHIN","DYNAMIC","EAGERLY","EARNEST","EARNING","ECLIPSE","ECONOMY","EDITION","EDUCATE","EFFECTS","EFFORTS","ELASTIC","ELEMENT","EMBASSY","EMBRACE","EMERALD","EMOTION","EMPEROR","EMPOWER","ENDLESS","ENGINES","ENGLISH","ENHANCE","EPISODE","EQUALLY","EVENING","EVIDENT","EXACTLY","EXAMINE","EXAMPLE","EXCITED","EXECUTE","EXHIBIT","EXPENSE","EXPLAIN","EXPLORE","EXPRESS","EXTREME","FACTORY","FACULTY","FAILURE","FALLING","FANTASY","FASHION","FEATURE","FEDERAL","FEELING","FICTION","FIFTEEN","FIGHTER","FINANCE","FINDING","FISHING","FITNESS","FLIGHTS","FLOWERS","FOLDING","FOOTAGE","FOREIGN","FOREVER","FORMULA","FORTUNE","FORWARD","FOUNDER","FRAGILE","FREEDOM","FREEZER","FRIENDS","FURTHER","GALLERY","GATEWAY","GENERAL","GENUINE","GESTURE","GIGABIT","GLACIER","GLASSES","GLIMPSE","GODDESS","GOODBYE","GRADUAL","GRAMMAR","GRANDPA","GRAPHIC","GRAVITY","GROCERY","GROWING","HABITAT","HAIRCUT","HALFWAY","HANDFUL","HANGING","HAPPENS","HARMONY","HARVEST","HEALTHY","HEARING","HEIGHTS","HELPFUL","HIGHEST","HIGHWAY","HISTORY","HOLDING","HOLIDAY","HONESTY","HOPEFUL","HORIZON","HOSTAGE","HUNDRED","HUNTING","HUSBAND","ILLEGAL","ILLNESS","IMAGINE","IMPROVE","INCLUDE","INITIAL","INQUIRY","INSIGHT","INSTALL","INSTANT","INSTEAD","INTENSE","INVOLVE","JOURNAL","JOURNEY","JUSTICE","JUSTIFY","KICKING","KIDNAPP","KINGDOM","KITCHEN","KNOWING","LANTERN","LAUGHED","LAUNDRY","LEADING","LEARNED","LEATHER","LECTURE","LEISURE","LENGTHS","LESSONS","LIBERAL","LIBERTY","LIBRARY","LICENSE","LIGHTED","LIMITED","LISTING","LITERAL","LOGICAL","LOOKING","LOTTERY","LUGGAGE","MACHINE","MAGICAL","MAILBOX","MAJESTY","MALWARE","MANAGER","MANDATE","MANKIND","MANSION","MARRIED","MARTIAL","MASSIVE","MASTERY","MAXIMUM","MEANING","MEASURE","MEDICAL","MEETING","MENTION","MESSAGE","METHODS","MILEAGE","MILLION","MINERAL","MINIMAL","MINIMUM","MIRACLE","MISSING","MISSION","MISTAKE","MIXTURE","MODESTY","MONARCH","MONSTER","MONTHLY","MORNING","MUSICAL","MYSTERY","NATURAL","NETWORK","NEUTRAL","NOTHING","NOWHERE","NUCLEAR","NUMBERS","NURSERY","OAKTREE","OBJECTS","OBSERVE","OBVIOUS","OFFENSE","OFFICER","OLYMPIC","ONGOING","OPENING","OPERATE","OPINION","OPTICAL","OPTIMAL","ORCHARD","ORGANIC","OUTCOME","OUTDOOR","OUTLINE","OUTLOOK","OUTSIDE","OVERALL","PACKAGE","PAINTER","PAJAMAS","PALETTE","PANCAKE","PARADOX","PARENTS","PARKING","PARTNER","PASSAGE","PASSION","PATIENT","PATTERN","PAYMENT","PENALTY","PENSION","PERCENT","PERFECT","PERFORM","PHANTOM","PHYSICS","PICTURE","PIONEER","PLASTIC","PLAYING","POINTER","POLICER","POLITIC","POPULAR","PORTION","POVERTY","PREDICT","PREPARE","PRESENT","PREVENT","PRIMARY","PRINTER","PRIVACY","PRIVATE","PROBLEM","PROCEED","PROCESS","PRODUCE","PRODUCT","PROFILE","PROGRAM","PROJECT","PROMISE","PROPOSE","PROTECT","PROTEIN","PROTEST","PROVIDE","PUBLISH","PURPOSE","PYRAMID","QUALITY","QUANTUM","QUARTER","QUERIES","RADIANT","RADICAL","RAILWAY","RAINBOW","READING","REALITY","REALIZE","RECEIVE","RECIPES","RECORDS","RECOVER","RECRUIT","REFLECT","REFUGEE","REGULAR","RELATED","RELEASE","REMAINS","REQUIRE","RESERVE","RESOLVE","RESPECT","RESPOND","RESTORE","RESULTS","RETIRED","REVENUE","REVERSE","ROMANCE","ROUTINE","RUNNING","SAILING","SAMPLES","SCANDAL","SCENERY","SCHOLAR","SCIENCE","SEAFOOD","SEATING","SECRETS","SECTION","SEEKING","SEGMENT","SELLING","SEMINAR","SENATOR","SENDING","SENSORY","SERIOUS","SERVANT","SERVICE","SESSION","SETTING","SEVENTH","SEVERAL","SHALLOW","SHELTER","SHINING","SHOCKED","SHORTLY","SHOWING","SIBLING","SILENCE","SILICON","SIMILAR","SINCERE","SINGING","SITTING","SIXTEEN","SKILLED","SLIDING","SMILING","SMOKING","SOCIETY","SOLDIER","SOMEHOW","SOMEONE","SPANISH","SPEAKER","SPECIAL","SPECIES","SPECTRE","SPONSOR","STADIUM","STARTUP","STATION","STATUES","STAYING","STEALTH","STELLAR","STOMACH","STORAGE","STORIES","STRANGE","STRETCH","STRIKES","STUDENT","STUDIES","STUFFED","SUBJECT","SUCCEED","SUCCESS","SUGGEST","SUICIDE","SUPPORT","SUPPOSE","SUPREME","SURFACE","SURGEON","SURGERY","SURVIVE","SUSPECT","SWALLOW","SWEATER","SYMPTOM","SYSTEMS","TALKING","TANGENT","TEACHER","TELLING","TENSION","TERMITE","TESTIFY","TESTING","THEATER","THERAPY","THIRSTY","THOUGHT","THREATS","THROUGH","TICKETS","TOBACCO","TOILETS","TONIGHT","TORNADO","TOURIST","TOWARDS","TRACTOR","TRADING","TRAFFIC","TRAGEDY","TRAILER","TRAINED","TRAINER","TRANSIT","TRAPPED","TREASON","TREATED","TRIUMPH","TROUBLE","TRUSTEE","TUESDAY","TUITION","TURNING","TWELFTH","TYPICAL","UNIFORM","UNKNOWN","UNUSUAL","UPGRADE","USUALLY","UTILITY","VACCINE","VAMPIRE","VANILLA","VARIETY","VARIOUS","VEHICLE","VENTURE","VERSION","VETERAN","VICTORY","VILLAGE","VINTAGE","VIOLATE","VIRTUAL","VISIBLE","VISITOR","VITAMIN","VOLCANO","WAITING","WALKING","WARNING","WARRIOR","WASHING","WEALTHY","WEATHER","WEBSITE","WEDDING","WEEKEND","WELCOME","WELFARE","WESTERN","WHETHER","WHISPER","WILLING","WINDING","WINNING","WITHOUT","WITNESS","WONDERS","WORKING","WORRIED","WRITING","YOUNGER","ZEALOUS"]; 
const W8=["ABSOLUTE","ACCIDENT","ACTIVITY","ADDITION","ADVANCED","AIRCRAFT","ALLIANCE","ANYTHING","ANYWHERE","APPROACH","ATTITUDE","AUDIENCE","BASEBALL","BEHAVIOR","BOUNDARY","BUILDING","BUSINESS","CALENDAR","CAMPAIGN","CAPACITY","CARRIAGE","CATEGORY","CEMETERY","CHAMPION","CHEMICAL","CHILDREN","CIRCULAR","CITIZENS","CLINICAL","COLORFUL","COLUMBIA","COMPOUND","COMPUTER","CONCLUDE","CONCRETE","CONFLICT","CONSIDER","CONSTANT","CONSUMER","CONTINUE","CONTRACT","CONTRAST","CONVINCE","CREATION","CREATIVE","CRIMINAL","CRITICAL","CULTURAL","CURRENCY","CUSTOMER","DATABASE","DAUGHTER","DAYLIGHT","DEADLINE","DECISION","DECREASE","DEFENDER","DELIVERY","DEMANDED","DEPARTED","DESIGNER","DIALOGUE","DIAMONDS","DINOSAUR","DIRECTOR","DISASTER","DISCOUNT","DISCOVER","DISEASES","DISTANCE","DISTRICT","DIVIDEND","DIVISION","DOCUMENT","DOMESTIC","DOMINANT","DRAMATIC","EARNINGS","ECONOMIC","EDUCATOR","ELECTION","ELEVATOR","ELIGIBLE","EMISSION","EMOTIONS","EMPLOYEE","EMPLOYER","ENDEAVOR","ENGINEER","ENORMOUS","ENTRANCE","ENVELOPE","EQUALITY","EQUATION","ESTIMATE","EVALUATE","EVERYDAY","EVERYONE","EVIDENCE","EXCHANGE","EXCITING","EXERCISE","EXPECTED","EXPENSES","EXPOSURE","EXTERNAL","FACILITY","FAMILIAR","FAVORITE","FESTIVAL","FIELDING","FIGHTING","FINANCES","FOOTBALL","FORECAST","FOUNTAIN","FOURTEEN","FRACTION","FREQUENT","FRIENDLY","FUNCTION","GENERATE","GOODNESS","GOVERNOR","GRADUATE","GREATEST","GREETING","GUARDIAN","GUIDANCE","HANDLING","HARDWARE","HEADACHE","HEADINGS","HERITAGE","HOSPITAL","HUMANITY","HUSBANDS","IDENTIFY","IDENTITY","ILLUSION","IMMUNITY","IMPERIAL","INCIDENT","INCLUDED","INCLUDES","INCREASE","INDUSTRY","INFECTED","INFORMAL","INHERENT","INNOCENT","INSTANCE","INTIMATE","INVASION","INVOLVED","ISOLATED","JUDGMENT","KANGAROO","KEYBOARD","LANDLORD","LANGUAGE","LAUGHTER","LEARNING","LITERARY","LOCATION","MACARONI","MAGAZINE","MAJORITY","MANAGING","MATERIAL","MAXIMIZE","MEASURED","MECHANIC","MEDICINE","MERCHANT","MINORITY","MISTAKES","MOBILITY","MONOPOLY","MONUMENT","MORTGAGE","MOVEMENT","MULTIPLE","MUSHROOM","MUSICIAN","NATIONAL","NEGATIVE","NORTHERN","NOTEBOOK","OBSERVER","OBSTACLE","OCCASION","OFFENDER","OFFICIAL","OPERATOR","OPPONENT","OPPOSITE","ORIGINAL","OUTBREAK","OUTCOMES","OVERSEAS","PAINTING","PARALLEL","PARTNERS","PASSPORT","PATIENCE","PEACEFUL","PERCEIVE","PERFORMS","PERSONAL","PHYSICAL","PICTURES","PLANNING","PLATFORM","PLEASANT","PLEASURE","POLITICS","PORTRAIT","POSITION","POSITIVE","POTATOES","PRACTICE","PRECIOUS","PRESENCE","PRESERVE","PRESSURE","PREVIOUS","PRINCESS","PRIORITY","PROBABLY","PROCEEDS","PRODUCER","PROGRAMS","PROGRESS","PROPERTY","PROPOSAL","PROPOSED","PROSPECT","PROTOCOL","PROVIDER","PROVINCE","PURCHASE","QUANTITY","QUARTERS","QUESTION","REACTION","RECEIPTS","RECEIVED","RECEIVER","RECOVERY","REGIONAL","REGISTER","REGISTRY","REJECTED","RELATIVE","RELIABLE","RELIGION","REMEMBER","REPLACED","REPORTED","REPORTER","REPUBLIC","REQUIRED","RESEARCH","RESERVES","RESIDENT","RESOURCE","RESPONSE","RESTRICT","REVENUES","REVISION","RHYTHMIC","ROMANTIC","ROUTINES","SANDWICH","SATURDAY","SCHEDULE","SCISSORS","SECURITY","SEGMENTS","SELECTED","SEMINARS","SENTENCE","SEPARATE","SEQUENCE","SERGEANT","SERVICES","SESSIONS","SHORTAGE","SHOULDER","SICKNESS","SOFTWARE","SOLDIERS","SOLUTION","SOMEBODY","SOMETIME","SOMEWHAT","SOUTHERN","SPECIFIC","SPECIMEN","SPECTRUM","SPENDING","SPONSORS","STANDARD","STANDING","STARTING","STEERING","STRANGER","STRATEGY","STRENGTH","STRIKING","STRUGGLE","STUDENTS","STUNNING","SUBJECTS","SURPRISE","SURVIVAL","SURVIVOR","SYLLABLE","SYMPTOMS","SYNDROME","TEACHERS","TEACHING","TEENAGER","TENDENCY","TERRIBLE","THEATERS","THEOLOGY","THEOREMS","THINKING","THIRTEEN","THOROUGH","THOUGHTS","THOUSAND","THREATEN","THURSDAY","TOGETHER","TOMORROW","TRAINING","TRANSFER","TREASURE","TRIANGLE","TROPICAL","TURNOVER","TWILIGHT","ULTIMATE","UMBRELLA","UNIVERSE","VACATION","VALUABLE","VARIABLE","VEHICLES","VERTICAL","VETERANS","VICTORIA","VILLAGER","VIOLENCE","VISITORS","VITAMINS","VOLCANIC","WAITRESS","WARDROBE","WARRANTY","WARRIORS","WATCHING","WATERWAY","WEAKNESS","WHATEVER","WHENEVER","WHEREVER","WILDLIFE","WINDMILL","WONDERED","WOODLAND","WORKSHOP","WRESTLER"];
const W9=["COALITION","DIAGNOSIS","PREDATORY","SCIENTIST","SEVENTEEN","SPIRITUAL","SUBSTANCE","VOLUNTEER","WANDERING","WORLDWIDE","YESTERDAY","ABANDONED","ABSORBING","ACQUIRING","ADVANTAGE","ADVENTURE","ALONGSIDE","AMBIGUOUS","ANIMATION","ANNOUNCES","APARTMENT","APPLIANCE","AWARENESS","BACKSTAGE","BALANCING","BAPTIZING","BEAUTIFUL","BEGINNING","BELONGING","BILLBOARD","BLUEPRINT","BOULEVARD","BREAKAWAY","BROADCAST","BUTTERFLY","CALCULATE","CAPTIVATE","CATALOGUE","CELEBRATE","CERTAINLY","CHALLENGE","CHAMELEON","CHAMPAGNE","CHARACTER","CHEMISTRY","CHILDHOOD","CHRISTMAS","CHRONICLE","CIGARETTE","CINNAMON","CLASSROOM","CLOCKWISE","COMMANDER","COMMUNITY","COMPANION","COMPLIANT","COMPOSING","COMPUTING","CONDITION","CONFRONT","CONNECTED","CONQUERED","CONSCIOUS","CONSTRUCT","CONTAINER","CONTINENT","CORPORATE","CROCODILE","DANGEROUS","DECEPTION","DECLINING","DECORATED","DEDICATED","DEFENSIVE","DELICIOUS","DEMANDING","DEMOCRACY","DEPARTURE","DEPRESSED","DESCRIBER","DESPERATE","DETECTING","DETERMINE","DEVELOPED","DIFFERENT","DIMENSION","DIRECTING","DIRECTORY","DISAPPEAR","DISCHARGE","DISCOVERY","DISMANTLE","DISRUPTED","DIZZINESS","DOUBTLESS","DWELLINGS","ECONOMICS","EDUCATING","EDUCATION","EFFECTIVE","ELABORATE","ELECTRODE","ELIMINATE","EMBRACING","EMERGENCY","EMOTIONAL","EMPOWERED","ENCOUNTER","ENDEAVOUR","ENDLESSLY","ENHANCING","ENJOYABLE","ENJOYMENT","ENROLMENT","ENTERTAIN","EQUIPMENT","ESSENTIAL","ESTABLISH","ESTIMATED","ESTIMATOR","EVALUATED","EVERYBODY","EVOLUTION","EXAMINING","EXCELLENT","EXCEPTION","EXCESSIVE","EXCLUSIVE","EXECUTIVE","EXISTENCE","EXPANDING","EXPANSION","EXPECTING","EXPEDIENT","EXPENSIVE","EXPLAINED","EXPLODING","EXPLORING","EXPLOSION","EXPORTING","EXTENDING","EXTENSION","EXTREMELY","FABRICATE","FACINATED","FANTASTIC","FAVOURITE","FEROCIOUS","FINANCIAL","FINGERTIP","FIREPLACE","FISHERMAN","FLOWERING","FOLLOWING","FOOTPRINT","FORBIDDEN","FOREIGNER","FORMATION","FORTNIGHT","FRAMEWORK","FRANCHISE","FREQUENCY","FRESHNESS","FRONTLINE","FURNITURE","GARDENING","GENTLEMAN","GEOGRAPHY","GOVERNING","GRADUALLY","GRATITUDE","GUARANTEE","GUIDELINE","GYMNASTIC","HANDCRAFT","HAPPENING","HAPPINESS","HARBORING","HARMONIZE","HEARTBEAT","HEPATITIS","HESITATER","HISTORIAN","HOUSEHOLD","HURRICANE","IDENTICAL","IMAGINARY","IMBALANCE","IMMEDIATE","IMMIGRANT","IMPACTING","IMPORTING","IMPORTANT","IMPROVING","INCLUDING","INCUMBENT","INDICATOR","INFECTION","INFLUENCE","INFORMING","INHERITED","INJECTION","INNOCENCE","INNOVATOR","INSPECTOR","INSTALLED","INSTANTLY","INSTITUTE","INSURANCE","INTELLECT","INTENDING","INTENSITY","INTENTION","INTERCEPT","INTERFACE","INTERPRET","INTERVENE","INTERVIEW","INTRODUCE","INTROVERT","INVENTORY","INVESTING","INVISIBLE","INVOLVING","IRREGULAR","ISOLATING","ISOLATION","ITINERARY","JUSTIFIED","JUSTIFIER","LABELLING","LANDSCAPE","LAUNCHING","LEGISLATE","LIABILITY","LIBRARIAN","LIGHTNING","LIMESTONE","LINGERING","LISTENING","LITERALLY","MAGNITUDE","MANDATORY","MARKETEER","MARKETING","MEANWHILE","MEASURING","MECHANISM","MEDIATING","MEMORABLE","MESSAGING","MICROWAVE","MIGRATION","MINIATURE","MODELLING","MONASTERY","MOTHERING","MOTIVATED","MUNICIPAL","MUSTERING","NARRATIVE","NATURALLY","NAVIGATED","NECESSARY","NEGOTIATE","NERVOUSLY","NEWSPAPER","NIGHTMARE","NORMALITY","OBJECTING","OBJECTIVE","OBSERVING","OBTAINING","OCCUPYING","OCCURRING","OFFENSIVE","OPERATING","OPERATION","ORGANISER","OUTSIDERS","OUTSKIRTS","OUTWITTED","OWNERSHIP","PACKAGING","PANICKING","PARAGRAPH","PATENTING","PERMITTED","PERSONNEL","PHENOMENA","PHYSICIAN","PLACEMENT","PLANTATION","PNEUMONIA","POLICEMAN","POLITICAL","POLLUTION","POPCORNER","POSSESSED","POTENTIAL","PRECEDING","PRECISION","PREDICTOR","PREFERRED","PREJUDICE","PREMATURE","PREPARING","PRESENTED","PRESERVES","PRESIDENT","PREVAILED","PREVALENT","PREVENTED","PRIMARILY","PRIMITIVE","PRINCIPAL","PRINCIPLE","PRISONERS","PRIVATELY","PRIVILEGE","PROACTIVE","PROBATION","PROCEEDED","PROCESSOR","PROCLAIMS","PRODUCING","PROFESSOR","PROFILING","PROGRAMME","PROJECTOR","PROMINENT","PROMISING","PROMOTERS","PROMOTION","PROPONENT","PROPOSING","PROSECUTE","PROTECTED","PROTECTOR","PROVIDING","PROVISION","PROXIMITY","PUBLISHER","PUBLISHED","PUNISHING","PURCHASED","PURPOSELY","QUARTERLY","RADIATING","REBELLION","RECEPTIVE","RECKONING","RECOGNIZE","RECOMMEND","RECORDING","RECOVERED","RECTANGLE","RECYCLING","REDUCTION","REFERENCE","REFLECTED","REFORMING","REGARDING","REGISTERS","REGULATOR","REHEARSAL","REINFORCE","RELATIONS","RELEVANCE","RELUCTANT","REMAINDER","REMAINING","REMINDING","RENDERING","RENEWABLE","REPLACING","REPORTING","REPRESENT","REPRODUCE","REPUTABLE","REQUIRING","RESHAPING","RESIDENTS","RESOLVING","RESONANCE","RESOURCES","RESPONDED","RESTORING","RESTRAINT","RESULTING","RETAILING","RETURNING","REVEALING","REVOLVING","RIDICULED","ROADBLOCK","ROCKETEER","SANCTUARY","SATISFIED","SCATTERED","SCREENING","SCRUTINCE","SEARCHING","SECONDARY","SECRETARY","SELECTING","SELECTION","SENSATION","SENSITIVE","SERIOUSLY","SERVICING","SHRINKING","SIDELINER","SIGNALING","SIGNATURE","SIMILARLY","SIMPLETON","SIMULATED","SITUATION","SLEEPLESS","SMUGGLING","SNOWBOARD","SOLICITOR","SOMETHING","SOMEWHERE","SORROWFUL","SOUTHEAST","SOUTHWEST","SOVEREIGN","SPACECRAFT","SPECIALLY","SPECIFICS","SPECULATE","SPOTLIGHT","SPREADING","SQUEEZING","STAIRCASE","STAMPEDED","STANDSTILL","STARTLING","STATEMENT","STATIONED","STEADFAST","STEADYING","STEAMSHIP","STOCKPILE","STRATEGIC","STREAMING","STRETCHED","STRICTEST","STRONGEST","STRUCTURE","STUMBLING","SUBMARINE","SUBMITTED","SUCCESSOR","SUFFERING","SUGGESTED","SUMMARIES","SUMPTUOUS","SUPERBOWL","SUPERHERO","SUPERVISE","SUPPLYING","SUPPORTED","SUPPORTER","SUPPOSING","SUPREMACY","SURPRISED","SURRENDER","SURROGATE","SURVEYING","SURVIVING","SUSPECTED","SUSPENDED","SUSPICION","SUSTAINED","SWITCHING","SYMBOLIZE","SYNAGOGUE","TECHNIQUE","TELEPHONE","TELESCOPE","TEMPORARY","TERMINATE","TERRITORY","TERRORISM","TERRORIST","TESTIFIER","THEREFORE","THICKENED","THRILLING","THRESHOLD","TIGHTENED","TIMESTAMP","TOLERANCE","TRADITION","TRAINLOAD","TRANSFORM","TRANSLATE","TRANSPORT","TRAVELING","TREATMENT","TREMBLING","TRIGGERED","TURBULENT","UNDERWENT","UNDERLINE","UNDERTAKE","UNFAILING","UNFOLDING","UNIFORMED","UNIVERSAL","UNLIMITED","UNOTICED","UNPLUGGED","UNRELATED","UNSETTLED","UNTOUCHED","UPGRADING","VALUATION","VARIATION","VEGETABLE","VENTILATE","VENTURING","VERSATILE","VIOLATION","VIRTUALLY","WANDERERS","WAREHOUSE","WELLBEING","WHOLESALE","WITHDRAWN","WONDERFUL","WONDERING","WRESTLING","YACHTSM"];
const ALL=[...W3,...W4,...W5,...W6];
const SKEY='dw-stats';
let lockedCols=[], maxG=6,answer='',aWord='',digCnt=0,row=0,col=0,guess=[],over=false;
let sndOn=true,matOn=true,hard=false,coopMode=false,curPlayer=1,stats=ldSt(),kbState={},extraHintStr='',isAnimating=false;
let shuffleBag=[];
let audioCtx=null,particles=[];
let timeLeft = 180, timerInt = null, idleTime = 0, hintsGiven = 0;
function ac(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();return audioCtx;}
function snd(t, v=1){
if(!sndOn)return;const c=ac(),n=c.currentTime,o=c.createOscillator(),g=c.createGain();o.connect(g).connect(c.destination);
if(t==='type'){o.type='square';o.frequency.setValueAtTime(700+Math.random()*500,n);g.gain.setValueAtTime(.05*v,n);g.gain.exponentialRampToValueAtTime(.001,n+.07);o.start(n);o.stop(n+.07);}
else if(t==='del'){o.type='sawtooth';o.frequency.setValueAtTime(300,n);o.frequency.exponentialRampToValueAtTime(100,n+.1);g.gain.setValueAtTime(.05*v,n);g.gain.exponentialRampToValueAtTime(.001,n+.1);o.start(n);o.stop(n+.1);}
else if(t==='flip'){o.type='sine';o.frequency.setValueAtTime(500,n);o.frequency.linearRampToValueAtTime(700,n+.06);g.gain.setValueAtTime(.04*v,n);g.gain.exponentialRampToValueAtTime(.001,n+.1);o.start(n);o.stop(n+.1);}
else if(t==='pop_c'){o.type='sine';o.frequency.setValueAtTime(600,n);o.frequency.exponentialRampToValueAtTime(1000,n+.12);g.gain.setValueAtTime(.08*v,n);g.gain.exponentialRampToValueAtTime(.001,n+.12);o.start(n);o.stop(n+.12);}
else if(t==='pop_p'){o.type='triangle';o.frequency.setValueAtTime(400,n);o.frequency.exponentialRampToValueAtTime(600,n+.1);g.gain.setValueAtTime(.06*v,n);g.gain.exponentialRampToValueAtTime(.001,n+.1);o.start(n);o.stop(n+.1);}
else if(t==='err'){o.type='square';o.frequency.setValueAtTime(150,n);g.gain.setValueAtTime(.06*v,n);g.gain.exponentialRampToValueAtTime(.001,n+.2);o.start(n);o.stop(n+.2);}
else if(t==='slam'){o.type='triangle';o.frequency.setValueAtTime(200+Math.random()*300,n);g.gain.setValueAtTime(.07*v,n);g.gain.exponentialRampToValueAtTime(.001,n+.06);o.start(n);o.stop(n+.06);}
else if(t==='win'){[523,587,659,784,880,1047].forEach((f,i)=>{const os=c.createOscillator(),gs=c.createGain();os.type='sine';os.frequency.setValueAtTime(f,n+i*.11);gs.gain.setValueAtTime(.08*v,n+i*.11);gs.gain.exponentialRampToValueAtTime(.001,n+i*.11+.28);os.connect(gs).connect(c.destination);os.start(n+i*.11);os.stop(n+i*.11+.28);});return;}
else if(t==='lose'){[400,350,300,250].forEach((f,i)=>{const os=c.createOscillator(),gs=c.createGain();os.type='triangle';os.frequency.setValueAtTime(f,n+i*.18);gs.gain.setValueAtTime(.07*v,n+i*.18);gs.gain.exponentialRampToValueAtTime(.001,n+i*.18+.3);os.connect(gs).connect(c.destination);os.start(n+i*.18);os.stop(n+i*.18+.3);});return;}
}
function startTimer() {
    if(timerInt) clearInterval(timerInt);
    timerInt = setInterval(() => {
        if(over || isAnimating || document.querySelector('.modal-overlay.show') || document.getElementById('eh-content')) return;
        timeLeft--;
        idleTime++;
        updateTimeDisp();
        
        if(timeLeft <= 0) {
            clearInterval(timerInt);
            snd('lose');
            over = true;
            updSt(false, 0);
            showRes(false, 0);
        } else if (idleTime >= 30 && !hard) {
            idleTime = 0;
            triggerAutoHint();
        }
    }, 1000);
}
function updateTimeDisp() {
    const td = document.getElementById('time-display');
    if(!td) return;
    const m = Math.floor(timeLeft/60).toString().padStart(2,'0');
    const s = (timeLeft%60).toString().padStart(2,'0');
    td.textContent = m + ':' + s;
    if(timeLeft <= 30) td.style.color = '#ff3366';
    else td.style.color = 'var(--gold)';
}
function triggerAutoHint() {
    let wl = aWord.length;
    let maxH = 2;
    if (wl === 6) maxH = 3;
    else if (wl === 7) maxH = 4;
    else if (wl === 8) maxH = 3;
    else if (wl >= 9) maxH = 4;

    if(hintsGiven >= maxH) return;
    
    let u=[];for(let i=0;i<wl;i++){if(!lockedCols[i*2])u.push(i);}
    if(u.length > 0) {
        let cnt = 1;
        if (wl === 8) cnt = 2;
        else if (wl >= 9) cnt = (hintsGiven < 3) ? 2 : 1;
        
        hintsGiven++;
        toast(`고민이 길어지네요! 자동 힌트 💡 (${hintsGiven}/${maxH})`);
        showExtraHint(null, cnt);
    }
}
function initMatrix(){
const c=document.getElementById('matrix-canvas'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;
const fs=14,cols=Math.floor(c.width/fs),dr=new Array(cols).fill(1);
!function d(){if(!matOn){x.clearRect(0,0,c.width,c.height);requestAnimationFrame(d);return;}
x.fillStyle='rgba(10,10,15,.08)';x.fillRect(0,0,c.width,c.height);x.fillStyle='#00ff8844';x.font=fs+'px JetBrains Mono';
for(let i=0;i<dr.length;i++){x.fillText('0123456789'[~~(Math.random()*10)],i*fs,dr[i]*fs);if(dr[i]*fs>c.height&&Math.random()>.975)dr[i]=0;dr[i]++;}
requestAnimationFrame(d);}();
addEventListener('resize',()=>{c.width=innerWidth;c.height=innerHeight;});
}
function spP(x,y,cl,n=15){for(let i=0;i<n;i++){const a=Math.PI*2*i/n+(Math.random()-.5)*.5,s=2+Math.random()*4;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:1,dc:.015+Math.random()*.02,sz:2+Math.random()*3,cl});}}
function initPart(){
const c=document.getElementById('particle-canvas'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;
!function a(){x.clearRect(0,0,c.width,c.height);for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx;p.y+=p.vy;p.vy+=.08;p.life-=p.dc;if(p.life<=0){particles.splice(i,1);continue;}x.globalAlpha=p.life;x.fillStyle=p.cl;x.beginPath();x.arc(p.x,p.y,p.sz*p.life,0,Math.PI*2);x.fill();}x.globalAlpha=1;requestAnimationFrame(a);}();
addEventListener('resize',()=>{c.width=innerWidth;c.height=innerHeight;});
}
function w2d(w){return w.split('').map(c=>(c.charCodeAt(0)-64).toString().padStart(2,'0')).join('');}
function buildRef(){
const el=document.getElementById('alpha-ref');el.innerHTML='';
for(let i=0;i<26;i++){const s=document.createElement('span');s.innerHTML='<b>'+String.fromCharCode(65+i)+'</b>='+(i+1).toString().padStart(2,'0');el.appendChild(s);}
}
function createBoard(){
const b=document.getElementById('game-board');b.innerHTML='';
if(aWord.length>=8) {
    b.classList.add('boss-board');
    if(aWord.length===10) b.classList.add('egg-board');
    else b.classList.remove('egg-board');
} else {
    b.classList.remove('boss-board', 'egg-board');
}
for(let r=0;r<maxG;r++){const rv=document.createElement('div');rv.className='board-row';rv.id='row-'+r;
for(let c=0;c<digCnt;c++){if(c>0&&c%2===0){const g=document.createElement('div');g.className='pg';rv.appendChild(g);}
const t=document.createElement('div');t.className='tile';t.id='tile-'+r+'-'+c;
t.onclick = () => { if(!over && !isAnimating && r === row && !lockedCols[c]) { col = c; updateAct(); } };
rv.appendChild(t);}
b.appendChild(rv);}
}
function deployTiles(){
const totalTiles=maxG*digCnt;let idx=0;
const isBoss=aWord.length>=8;
const volMod=isBoss?3.5:1+(aWord.length-3)*0.4;
const delayStep=isBoss?20:aWord.length>=7?25:aWord.length>=6?35:60;
for(let r=0;r<maxG;r++){for(let c=0;c<digCnt;c++){const t=document.getElementById('tile-'+r+'-'+c);
const delay=idx*delayStep;
setTimeout(()=>{
t.classList.add('deployed');
if(isBoss){
    if(aWord.length===10){
        t.style.boxShadow='0 0 25px #ff8800';t.style.borderColor='#ff8800';t.style.color='#ff8800';t.style.backgroundColor='transparent';
    } else {
        t.style.boxShadow='0 0 25px #ff3366';t.style.borderColor='#ff3366';t.style.color='#ff3366';
    }
    document.getElementById('app').style.transform=`translate(${(Math.random()-.5)*30}px, ${(Math.random()-.5)*30}px)`;setTimeout(()=>document.getElementById('app').style.transform='none',50);
}
snd(isBoss?'err':'slam',volMod);
},delay);
idx++;}}
const intensity=isBoss?40:1+(aWord.length-3)*1.2;
document.documentElement.style.setProperty('--si', intensity+'px');
document.documentElement.style.setProperty('--sr', (intensity*0.15)+'deg');
const shakeDur=isBoss?2000:300+(aWord.length-3)*150;
const app=document.getElementById('app');
setTimeout(()=>{
app.style.animation=`heavyShake ${shakeDur}ms ease`;
if(isBoss){snd('lose',3);document.documentElement.style.setProperty('--bg','#1a0008');setTimeout(()=>document.documentElement.style.setProperty('--bg','#0a0a0c'), shakeDur);}
setTimeout(()=>{app.style.animation='';},shakeDur);
},(totalTiles-1)*delayStep+80);
setTimeout(()=>{updateAct(); startTimer();},totalTiles*delayStep+300);
}
function updateAct(){document.querySelectorAll('.tile.active').forEach(t=>t.classList.remove('active'));if(over)return;const t=document.getElementById('tile-'+row+'-'+col);if(t)t.classList.add('active');}
function showTurnOverlay(p){
const pc=p===1?'#00e5ff':'#ff3366';const ov=document.createElement('div');
ov.style.cssText='position:fixed;inset:0;pointer-events:none;display:flex;align-items:center;justify-content:center;z-index:400;opacity:0;transition:opacity .3s;background:rgba(0,0,0,.4);backdrop-filter:blur(4px);';
const txt=document.createElement('h1');
txt.style.cssText=`font-family:var(--ff);font-size:3.5rem;color:${pc};text-shadow:0 0 20px ${pc};transform:scale(.5);transition:transform .4s cubic-bezier(.17,.67,.29,1.3);margin:0;`;
txt.innerHTML=`P${p} 차례!`;ov.appendChild(txt);document.body.appendChild(ov);
void ov.offsetWidth;ov.style.opacity='1';txt.style.transform='scale(1)';
setTimeout(()=>{ov.style.opacity='0';txt.style.transform='scale(1.2)';setTimeout(()=>ov.remove(),300);},1200);
}
function updateTurnUI(){const tt=document.getElementById('turn-text');tt.textContent='P'+curPlayer;tt.style.color=curPlayer===1?'#00e5ff':'#ff3366';}
function drawFromBag(){
if(shuffleBag.length===0){
shuffleBag=[3,3,3,4,4,4,4,5,5,5,5,6,6,7];
for(let i=shuffleBag.length-1;i>0;i--){
const j=Math.floor(Math.random()*(i+1));
[shuffleBag[i],shuffleBag[j]]=[shuffleBag[j],shuffleBag[i]];
}
}
return shuffleBag.pop();
}
function newGame(wonFlag=null, forceBoss=false, forceEgg=false, forceLength=null){
let tl=forceEgg ? 10 : forceBoss ? forceBoss : (forceLength ? forceLength : drawFromBag());
if(!forceBoss && !forceEgg && !forceLength){
    const roll = Math.random()*100;
    if(roll < 0.5) {
        tl=10;
        stats.bossProb=1.0;
    } else if(roll < stats.bossProb){
        tl=Math.random()<0.5?8:9;
        stats.bossProb=1.0;
    } else {
        stats.bossProb+=0.5;
    }
}
svSt();
const isBossTl=(tl===8||tl===9||tl===10);
const jd=document.getElementById('jackpot-display');
if(jd){
    if(tl===10){
        jd.textContent='🌟 EASTER EGG! 🌟';
        jd.style.color='#9933ff';
        jd.style.textShadow='0 0 10px #9933ff';
        jd.style.animation='popIn 0.5s infinite';
    }else if(tl===8||tl===9){
        jd.textContent='🚨 '+tl+'글자 BOSS! 🚨';
        jd.style.color='#ff3366';
        jd.style.textShadow='0 0 10px #ff3366';
        jd.style.animation='popIn 0.5s infinite';
    }else{
        jd.textContent='🔥 BOSS RATE: '+stats.bossProb.toFixed(1)+'%';
        jd.style.color='#ffcc00';
        jd.style.textShadow='0 0 5px #ffcc00';
        jd.style.animation='';
    }
}
const wm={3:W3,4:W4,5:W5,6:W6,7:W7,8:W8,9:W9,10:['MAPLESTORY']},arr=wm[tl]||W4;
aWord=arr[~~(Math.random()*arr.length)];answer=w2d(aWord);digCnt=answer.length;maxG=isBossTl?13:6+(aWord.length-3);
row=0;col=0;guess=new Array(digCnt).fill('');lockedCols=new Array(digCnt).fill(false);over=false;isAnimating=false;kbState={};extraHintStr='';
if(timerInt) clearInterval(timerInt);
timeLeft = 180; idleTime = 0; hintsGiven = 0;
updateTimeDisp();
const eggBg=document.getElementById('egg-bg');if(eggBg){if(tl===10){eggBg.style.display='block';eggBg.style.opacity='0';}else{eggBg.style.display='none';eggBg.style.opacity='0';}}
if(coopMode){curPlayer=Math.random()<0.5?1:2;updateTurnUI();setTimeout(()=>showTurnOverlay(curPlayer),isBossTl?2000:600);}
createBoard();deployTiles();updateHint();
document.getElementById('word-display').textContent='?'.repeat(aWord.length);
document.getElementById('result-overlay').classList.remove('show');
document.querySelectorAll('.kd').forEach(k=>{k.className='key kd';});
}

function updateTileText(r, c, text) {
    const t = document.getElementById('tile-'+r+'-'+c);
    if (!t) return;
    if(c%2 === 1) {
        const g1 = guess[c-1] || '';
        const g2 = guess[c] || '';
        let letter = '';
        if(g1 !== '' && g2 !== '') {
            let num = parseInt(g1+g2, 10);
            if(num >= 1 && num <= 26) {
                letter = String.fromCharCode(64 + num);
            }
        }
        t.innerHTML = text + '<span style="position:absolute; left:-2px; bottom:-14px; transform:translateX(-50%); font-size:1rem; color:#ffd700; font-weight:900; text-shadow:0 0 8px rgba(255,215,0,0.7), 0 0 3px rgba(255,215,0,0.4); pointer-events:none; font-family:var(--ff); z-index:10; letter-spacing:0.5px;">' + letter + '</span>';
    } else {
        t.textContent = text;
        if (c+1 < digCnt) {
            updateTileText(r, c+1, guess[c+1] || '');
        }
    }
}

function addD(d){
if(over||isAnimating)return;
if(col>=digCnt) {
    let firstEmpty = -1;
    for(let i=0; i<digCnt; i++) if(guess[i]==='' && !lockedCols[i]) { firstEmpty=i; break; }
    if (firstEmpty !== -1) col = firstEmpty;
    else return;
}
if(lockedCols[col]) return;
snd('type');
guess[col]=d;
const t=document.getElementById('tile-'+row+'-'+col);
updateTileText(row, col, d);
t.classList.remove('typing');
void t.offsetWidth;
t.classList.add('typing','filled');
let nextCol = col + 1;
while(nextCol < digCnt && (guess[nextCol] !== '' || lockedCols[nextCol])) nextCol++;
if(nextCol < digCnt) col = nextCol;
else if(col < digCnt - 1) col++; 
else col = digCnt;
updateAct();
}

function delD(){
if(over||isAnimating)return;
if(lockedCols[col]) return;
if(col>=0 && col<digCnt && guess[col]!=='') {
    snd('del');
    guess[col]='';
    const t=document.getElementById('tile-'+row+'-'+col);
    updateTileText(row, col, '');
    t.classList.remove('filled','typing');
} else {
    let p = col - 1;
    while(p >= 0 && lockedCols[p]) p--;
    if(p >= 0) {
        col = p;
        snd('del');
        guess[col]='';
        const t=document.getElementById('tile-'+row+'-'+col);
        updateTileText(row, col, '');
        t.classList.remove('filled','typing');
    }
}
updateAct();
}

function submit(){
if(over||isAnimating)return;
if(guess.includes('')){snd('err');toast(digCnt+'자리를 모두 입력하세요!');const el=document.getElementById('row-'+row);el.classList.add('shake-row');setTimeout(()=>el.classList.remove('shake-row'),500);return;}
let invalid=[];for(let i=0;i<digCnt;i+=2){if(lockedCols[i]&&lockedCols[i+1])continue;const pair=guess[i]+guess[i+1];const num=parseInt(pair,10);if(num<1||num>26)invalid.push(i);}
if(invalid.length>0){snd('err');toast('⚠️ 유효하지 않은 값! (01~26만 가능)');const el=document.getElementById('row-'+row);el.classList.add('shake-row');setTimeout(()=>el.classList.remove('shake-row'),500);invalid.forEach(idx=>{const t1=document.getElementById('tile-'+row+'-'+idx);const t2=document.getElementById('tile-'+row+'-'+(idx+1));if(t1)t1.classList.add('invalid-tile');if(t2)t2.classList.add('invalid-tile');setTimeout(()=>{if(t1){t1.classList.remove('invalid-tile','filled','typing');guess[idx]='';updateTileText(row,idx,'');}if(t2){t2.classList.remove('invalid-tile','filled','typing');guess[idx+1]='';updateTileText(row,idx+1,'');}col=invalid[0];updateAct();},1500);});return;}
isAnimating=true;
const g=guess.join(''),res=evaluate(g,answer);reveal(row,g,res);
}

function evaluate(g,a){
const r=new Array(digCnt).fill('absent'),ga=g.split(''),aa=a.split(''),used=new Array(digCnt).fill(false);
for(let i=0;i<digCnt;i++)if(ga[i]===aa[i]){r[i]='correct';used[i]=true;ga[i]=null;}
for(let i=0;i<digCnt;i++){if(!ga[i])continue;for(let j=0;j<digCnt;j++){if(!used[j]&&ga[i]===aa[j]){r[i]='present';used[j]=true;break;}}}
return r;
}
function reveal(rw,g,res){
const tiles=[];for(let c=0;c<digCnt;c++)tiles.push(document.getElementById('tile-'+rw+'-'+c));
const isW=res.every(r=>r==='correct');let done=0;
tiles.forEach((t,i)=>{
    setTimeout(()=>{
        t.style.boxShadow='';t.style.borderColor='';t.style.color='';t.style.backgroundColor='';
        t.classList.remove('filled','typing','reveal');
        t.classList.add(res[i]);
        if(res[i]==='correct')snd('pop_c');else if(res[i]==='present')snd('pop_p');else snd('del');
        updKb(g[i],res[i]);
        if(res[i]==='correct'){const rc=t.getBoundingClientRect();spP(rc.left+rc.width/2,rc.top+rc.height/2,'#00ff88',5);}
        done++;if(done===digCnt)onDone(isW);
    }, i*70);
});
}
function updKb(d,s){}
function onDone(isW){
if(isW){snd('win');over=true;isAnimating=false;
for(let c=0;c<digCnt;c++){const t=document.getElementById('tile-'+row+'-'+c);setTimeout(()=>t.classList.add('bounce'),c*60);}
setTimeout(()=>{for(let i=0;i<4;i++)setTimeout(()=>spP(innerWidth*(.2+Math.random()*.6),innerHeight*(.2+Math.random()*.4),['#00ff88','#00e5ff','#ffd700','#ff3366'][i%4],20),i*300);},400);
updSt(true,row+1);setTimeout(()=>showRes(true,row+1),1400);
}else{row++;if(aWord.length===10){const eggBg=document.getElementById('egg-bg');if(eggBg)eggBg.style.opacity=(row/(maxG-1)).toFixed(2);}
if(row>=maxG){if(coopMode){const r0=document.getElementById('row-'+(row-maxG));if(r0){r0.style.animation='fadeOutUp 0.3s forwards';setTimeout(()=>r0.remove(),300);}const b=document.getElementById('game-board'),rv=document.createElement('div');rv.className='board-row slide-up-new';rv.id='row-'+row;for(let c=0;c<digCnt;c++){if(c>0&&c%2===0){const g=document.createElement('div');g.className='pg';rv.appendChild(g);}const t=document.createElement('div');t.className='tile deployed';if(aWord.length===10){t.style.boxShadow='0 0 25px #ff8800';t.style.borderColor='#ff8800';t.style.color='#ff8800';t.style.backgroundColor='transparent';}else if(aWord.length>=8){t.style.boxShadow='0 0 25px #ff3366';t.style.borderColor='#ff3366';t.style.color='#ff3366';}t.id='tile-'+row+'-'+c;const r_cap=row;t.onclick=()=>{if(!over&&!isAnimating&&r_cap===row&&!lockedCols[c]){col=c;updateAct();}};rv.appendChild(t);}b.appendChild(rv);col=0;guess=new Array(digCnt).fill('');const nxt=()=>{isAnimating=false;curPlayer=curPlayer===1?2:1;updateTurnUI();showTurnOverlay(curPlayer);applyLockedHints();col=0;while(col<digCnt&&lockedCols[col])col++;updateAct();};setTimeout(nxt,300);}else{snd('lose');over=true;isAnimating=false;updSt(false,0);setTimeout(()=>showRes(false,0),700);}
}else{col=0;guess=new Array(digCnt).fill('');const nxt=()=>{isAnimating=false;if(coopMode){curPlayer=curPlayer===1?2:1;updateTurnUI();showTurnOverlay(curPlayer);}applyLockedHints();col=0;while(col<digCnt&&lockedCols[col])col++;updateAct();};
nxt();}}}
function applyLockedHints(){
for(let i=0;i<digCnt;i++){
if(lockedCols[i]){
guess[i]=answer[i];
const t=document.getElementById('tile-'+row+'-'+i);
if(t){t.classList.add('correct','filled');t.style.boxShadow='';t.style.borderColor='';t.style.color='';t.style.backgroundColor='';updateTileText(row,i,guess[i]);}
}}
}
function updateHint(){const el=document.getElementById('hint-text');if(hard){el.textContent='???';return;}if(extraHintStr){el.innerHTML=`💡 ${aWord.length}글자 <span style="color:var(--yellow)">${extraHintStr}</span>`;}else{el.textContent='💡 '+aWord.length+'글자 단어';}}
function showExtraHint(cb,forceCnt){
let u=[];for(let i=0;i<aWord.length;i++){if(!lockedCols[i*2])u.push(i);}
if(u.length===0){if(cb)cb();return;}
let cnt=forceCnt||1;
cnt=Math.min(cnt,u.length);
let hArr=[];
for(let i=0;i<cnt;i++){
    const idx=Math.floor(Math.random()*u.length);
    const hi=u[idx];
    hArr.push({p:hi+1,l:aWord[hi]});
    u.splice(idx,1);
}
hArr.sort((a,b)=>a.p-b.p);
const hs=hArr.map(h=>`${h.p}번째: '${h.l}'`).join(', ');
extraHintStr=(extraHintStr?extraHintStr+' / ':'')+'('+hs+')';
for(let h of hArr){
let hi=h.p-1; let ansStr=w2d(h.l); let c1=hi*2; let c2=hi*2+1;
guess[c1]=ansStr[0]; guess[c2]=ansStr[1];
lockedCols[c1]=true; lockedCols[c2]=true;
let t1=document.getElementById('tile-'+row+'-'+c1); let t2=document.getElementById('tile-'+row+'-'+c2);
if(t1){t1.classList.add('correct','filled');t1.style.boxShadow='';t1.style.borderColor='';t1.style.color='';t1.style.backgroundColor='';}
if(t2){t2.classList.add('correct','filled');t2.style.boxShadow='';t2.style.borderColor='';t2.style.color='';t2.style.backgroundColor='';}
updateTileText(row, c1, guess[c1]);
}
updateAct();
const ov=document.createElement('div');
ov.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,.85);backdrop-filter:blur(8px);z-index:500;display:flex;align-items:center;justify-content:center;flex-direction:column;cursor:pointer;opacity:0;transition:opacity .4s;';
ov.innerHTML=`<div style="transform:scale(.8);transition:transform .4s cubic-bezier(.17,.67,.29,1.3);text-align:center;" id="eh-content"><div style="font-size:4rem;margin-bottom:10px;animation:popIn 1s infinite;">💡</div><h2 style="font-family:var(--fb);color:var(--yellow);font-size:1.8rem;margin-bottom:10px;">추가 힌트</h2><p style="font-family:var(--fb);font-size:1.1rem;color:var(--text);">정답은 <strong style="color:var(--cyan);font-size:1.5rem;">${hs}</strong> 입니다!</p><p style="font-size:.8rem;color:var(--dim);margin-top:20px;">(화면을 터치하여 계속)</p></div>`;
document.body.appendChild(ov);
void ov.offsetWidth;ov.style.opacity='1';document.getElementById('eh-content').style.transform='scale(1)';
snd('flip');
ov.onclick=()=>{ov.style.opacity='0';document.getElementById('eh-content').style.transform='scale(1.2)';setTimeout(()=>{ov.remove();updateHint();if(cb)cb();},400);};
}
function toast(m){const c=document.getElementById('toast-container'),t=document.createElement('div');t.className='toast';t.textContent=m;c.appendChild(t);setTimeout(()=>t.remove(),2500);}
function showRes(won,att){
const ov=document.getElementById('result-overlay'),ct=document.getElementById('result-content');
const cd=answer.match(/.{2}/g).join(' ');
const msgs=['천재!🧠','놀라워요!🔥','완벽!✨','훌륭해요!👍','잘했어요!👏','좋아요!😊','나쁘지않아!🤔','겨우..😅','아슬아슬!😮‍💨'];
const eggGifs=document.getElementById('egg-gifs');
if(window.fwInt) clearInterval(window.fwInt);
if(window.gifReloadInt) clearInterval(window.gifReloadInt);
if(eggGifs){
    eggGifs.style.display=(won&&aWord.length===10)?'block':'none';
    if(won&&aWord.length===10) {
        window.gifReloadInt = setInterval(()=>{
            const imgs = eggGifs.querySelectorAll('img');
            imgs.forEach(i => { let src = i.src.split('?')[0]; i.src = src + '?t=' + Date.now(); });
        }, 13920);
        window.fwInt = setInterval(() => {
            spP(innerWidth*(.1+Math.random()*.8),innerHeight*(.1+Math.random()*.6),['#00ff88','#00e5ff','#ffd700','#ff3366','#ff8800'][Math.floor(Math.random()*5)],20);
        }, 600);
    }
}
let emojiHtml = '<div class="r-emoji">'+(won?'🎉':'💀')+'</div>';
if (aWord.length === 10) emojiHtml = '<div class="r-emoji"><img src="muchroom.png" style="width:60px; height:auto;"/></div>';
let wordStyle = (aWord === 'MAPLESTORY') ? 'color:#ff8800; text-shadow:0 0 15px #ff8800;' : '';
let titleText = won ? 'CORRECT!' : 'GAME OVER';
let subText = won ? msgs[Math.min(att-1, msgs.length-1)] : '다음에 도전!';
if (coopMode) {
    if (won) {
        titleText = 'P' + curPlayer + ' 승리! 🏆';
        subText = '축하합니다!';
    } else {
        titleText = '무승부! 🤝';
        subText = '둘 다 실패!';
    }
}
ct.innerHTML=emojiHtml+'<div class="r-title '+(won?'win':'lose')+'">'+titleText+'</div><p style="color:#888;font-size:.8rem;margin:6px 0">'+subText+'</p><div class="r-word" style="'+wordStyle+'">'+aWord+'</div><div class="r-code">'+cd+'</div><div class="r-btns"><button class="r-btn pri" id="rn">🔄 새 게임</button><button class="r-btn sec" id="rs">📋 공유</button></div>';
ov.classList.add('show');document.getElementById('word-display').textContent=aWord;
document.getElementById('rn').onclick=()=>{
    if(window.fwInt) clearInterval(window.fwInt);
    if(window.gifReloadInt) clearInterval(window.gifReloadInt);
    ov.classList.remove('show');
    setTimeout(()=>showStartScreen(won),300);
};
document.getElementById('rs').onclick=()=>{let t='Word→Number\n'+(won?att+'/'+maxG:'X/'+maxG)+'\n\n';const e=won?att:maxG;for(let r=0;r<e;r++){let l='';for(let c=0;c<digCnt;c++){const ti=document.getElementById('tile-'+r+'-'+c);l+=ti.classList.contains('correct')?'🟩':ti.classList.contains('present')?'🟨':'⬛';}t+=l+'\n';}navigator.clipboard.writeText(t).then(()=>toast('복사됨!')).catch(()=>toast('실패'));};
}
function dSt(){return{played:0,won:0,streak:0,maxStreak:0,dist:[0,0,0,0,0,0,0,0,0,0],bossProb:1.0};}
function ldSt(){try{const s=JSON.parse(localStorage.getItem(SKEY))||dSt();if(s.bossProb===undefined)s.bossProb=1.0;return s;}catch{return dSt();}}
function svSt(s=stats){localStorage.setItem(SKEY,JSON.stringify(s));}
function updSt(w,a){stats.played++;if(w){stats.won++;stats.streak++;if(stats.streak>stats.maxStreak)stats.maxStreak=stats.streak;while(stats.dist.length<10)stats.dist.push(0);stats.dist[a-1]++;}else stats.streak=0;svSt(stats);document.getElementById('streak-display').textContent='🔥'+stats.streak;}
function showSt(){
document.getElementById('stat-played').textContent=stats.played;
document.getElementById('stat-win-rate').textContent=stats.played?Math.round(stats.won/stats.played*100)+'%':'0%';
document.getElementById('stat-streak').textContent=stats.streak;
document.getElementById('stat-max-streak').textContent=stats.maxStreak;
const bc=document.getElementById('distribution-bars');bc.innerHTML='';const mx=Math.max(...stats.dist,1);
stats.dist.forEach((c,i)=>{const r=document.createElement('div');r.className='dist-row';r.innerHTML='<span class="dist-label">'+(i+1)+'</span><div class="dist-bar'+(c===mx&&c>0?' hl':'')+'" style="width:'+Math.max(c/mx*100,8)+'%">'+c+'</div>';bc.appendChild(r);});
document.getElementById('stats-modal').classList.add('show');
}
function hk(k){if(over||document.querySelector('.modal-overlay.show')||isAnimating)return;if(k>='0'&&k<='9')addD(k);else if(k==='Backspace'||k==='del')delD();else if(k==='Enter'||k==='ent')submit();else if(k==='ArrowLeft'){let p=col-1;while(p>=0&&lockedCols[p])p--;if(p>=0){col=p;updateAct();}}else if(k==='ArrowRight'){let p=col+1;while(p<digCnt&&lockedCols[p])p++;if(p<digCnt){col=p;updateAct();}}}
function initEv(){
document.addEventListener('keydown',e=>{if(document.querySelector('.modal-overlay.show'))return;if((e.key>='0'&&e.key<='9')||e.key==='Backspace'||e.key==='Enter'||e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();hk(e.key);}});
document.querySelectorAll('.key').forEach(b=>b.addEventListener('click',()=>hk(b.dataset.key)));
document.getElementById('test-boss8-btn').onclick=()=>{document.getElementById('result-overlay').classList.remove('show');document.getElementById('settings-modal').classList.remove('show');newGame(null,8,false);};
document.getElementById('test-boss9-btn').onclick=()=>{document.getElementById('result-overlay').classList.remove('show');document.getElementById('settings-modal').classList.remove('show');newGame(null,9,false);};
document.getElementById('test-egg-btn').onclick=()=>{document.getElementById('result-overlay').classList.remove('show');document.getElementById('settings-modal').classList.remove('show');newGame(null,false,true);};
document.getElementById('help-btn').onclick=()=>document.getElementById('help-modal').classList.add('show');
document.getElementById('help-close').onclick=()=>document.getElementById('help-modal').classList.remove('show');
document.getElementById('stats-btn').onclick=()=>{if(prompt("비밀번호를 입력하세요:")==="1214") showSt(); else alert("비밀번호가 틀렸습니다.");};
document.getElementById('stats-close').onclick=()=>document.getElementById('stats-modal').classList.remove('show');

const jpSlider = document.getElementById('jackpot-slider');
const jpValDisp = document.getElementById('jackpot-val-display');

document.getElementById('settings-btn').onclick=()=>{
    if(prompt("비밀번호를 입력하세요:")!=="1214") { alert("비밀번호가 틀렸습니다."); return; }
    document.getElementById('settings-modal').classList.add('show');
    jpSlider.value = stats.bossProb;
    jpValDisp.textContent = stats.bossProb.toFixed(1) + '%';
};
document.getElementById('settings-close').onclick=()=>document.getElementById('settings-modal').classList.remove('show');

jpSlider.oninput = (e) => {
    const val = parseFloat(e.target.value);
    stats.bossProb = val;
    jpValDisp.textContent = val.toFixed(1) + '%';
    svSt();
    const jd=document.getElementById('jackpot-display');
    if(jd && aWord.length<8) {
        jd.textContent='🔥 BOSS RATE: '+val.toFixed(1)+'%';
    }
};

document.getElementById('new-game-btn').onclick=()=>{document.getElementById('stats-modal').classList.remove('show');setTimeout(()=>showStartScreen(null),300);};
document.querySelectorAll('.modal-overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o)o.classList.remove('show');}));
document.getElementById('sound-toggle').onchange=e=>{sndOn=e.target.checked;};
document.getElementById('matrix-toggle').onchange=e=>{matOn=e.target.checked;};
document.getElementById('hard-toggle').onchange=e=>{hard=e.target.checked;updateHint();};
document.getElementById('coop-toggle').onchange=e=>{coopMode=e.target.checked;document.getElementById('turn-display').style.display=coopMode?'inline':'none';if(coopMode){curPlayer=Math.random()<0.5?1:2;updateTurnUI();toast('경쟁 모드 ON: 먼저 맞추면 승리!');}else{toast('경쟁 모드 OFF');}};
}
function showStartScreen(wonFlag=null){
const so=document.createElement('div');
so.style.cssText='position:fixed;inset:0;background:var(--bg);z-index:9999;display:flex;align-items:center;justify-content:center;flex-direction:column;cursor:pointer;transition:opacity .4s;overflow-y:auto;padding:20px;';
so.innerHTML=`<div style="max-width:520px;width:100%;display:flex;flex-direction:column;align-items:center;gap:16px;">
<h1 class="title" style="font-size:2.4rem;margin:0;text-align:center;"><span class="t-main">WORD → NUMBER</span></h1>
<p style="margin:0;color:var(--sub);font-size:0.9rem;text-align:center;line-height:1.6;">영어 단어를 <b style="color:var(--cyan)">숫자 코드</b>로 변환한 값을 맞추세요!<br><span style="color:var(--dim)">A=01, B=02 ... Z=26</span> &nbsp; <span style="color:var(--cyan)">예: LOVE → 12 15 22 05</span><br><span style="color:#ff3366;font-weight:bold;">⏱️ 제한 시간 3분! (오래 고민하면 힌트 제공)</span></p>
<div style="display:flex;justify-content:center;gap:16px;font-size:0.85rem;color:var(--sub);margin:-4px 0;">
<span>🟩 위치 맞음</span><span>🟨 포함됨</span><span>⬛ 없음</span>
</div>
<div style="width:100%;display:grid;grid-template-columns:1fr 1fr;gap:10px;">
<div style="background:rgba(0,255,136,0.05);border:1px solid rgba(0,255,136,0.15);border-radius:14px;padding:16px;text-align:center;">
<div style="font-size:1.8rem;margin-bottom:6px;">💡</div>
<p style="margin:0 0 4px;color:#00ff88;font-family:var(--fb);font-size:0.82rem;font-weight:700;">힌트 시스템</p>
<p style="margin:0;color:var(--sub);font-size:0.72rem;line-height:1.5;">30초가 지날 때마다 <span style="color:#00ff88;font-weight:600;">정답 타일</span> 자동 공개! (최대 2~4회)</p>
</div>
<div style="background:rgba(255,51,102,0.05);border:1px solid rgba(255,51,102,0.15);border-radius:14px;padding:16px;text-align:center;">
<div style="font-size:1.8rem;margin-bottom:6px;">🎁</div>
<p style="margin:0 0 4px;color:#ff3366;font-family:var(--fb);font-size:0.82rem;font-weight:700;">이벤트 보상</p>
<p style="margin:0;color:var(--sub);font-size:0.72rem;line-height:1.5;">🏅 <b style="color:#ffd700">도전만 해도 도장!</b><br>🍫 <b style="color:#00e5ff">정답 맞추면 간식!</b></p>
</div>
</div>
<details open style="width:100%;background:rgba(255,255,255,0.03);border:1px solid rgba(255,215,0,0.15);border-radius:14px;cursor:pointer;">
<summary style="padding:12px 16px;color:#ffd700;font-family:var(--fb);font-size:0.85rem;font-weight:700;list-style:none;display:flex;align-items:center;gap:8px;user-select:none;">📋 알파벳 ↔ 숫자 변환표 <span style="color:var(--dim);font-size:0.7rem;font-weight:400;margin-left:auto;">▼ 펼치기</span></summary>
<div style="padding:4px 16px 14px;display:flex;flex-wrap:wrap;justify-content:center;gap:3px 5px;font-family:var(--fm);font-size:0.7rem;color:var(--sub);">
${'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').map((l,i)=>'<span style="background:rgba(255,255,255,0.06);padding:2px 5px;border-radius:4px;"><b style=\\"color:#ffd700\\">'+l+'</b>='+(i+1).toString().padStart(2,'0')+'</span>').join('')}
</div>
</details>
<div style="margin-top:4px;text-align:center;">
<p style="color:var(--cyan);font-family:var(--fb);font-size:1.2rem;font-weight:700;animation:popIn 1s infinite;margin:0;">화면을 터치하여 게임 시작</p>
</div>
</div>`;
document.body.appendChild(so);
so.onclick=()=>{if(ac().state==='suspended')ac().resume();so.style.opacity='0';setTimeout(()=>{so.remove();newGame(wonFlag);},400);};
}
function init(){
initMatrix();initPart();buildRef();initEv();document.getElementById('streak-display').textContent='🔥'+stats.streak;
showStartScreen();
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
