const fs = require('fs');

let W8 = ["ABSOLUTE", "ACCIDENT", "ACTIVITY", "ADDITION", "ADVANCED", "AIRCRAFT", "ALLIANCE", "ANYTHING", "ANYWHERE", "APPROACH", "ATTITUDE", "AUDIENCE", "BASEBALL", "BEAUTY", "BEHAVIOR", "BOUNDARY", "BUILDING", "BUSINESS", "CALENDAR", "CAMPAIGN", "CAPACITY", "CARRIAGE", "CATEGORY", "CEMETERY", "CHAMPION", "CHEMICAL", "CHILDREN", "CIRCULAR", "CITIZENS", "CLINICAL", "COALITION", "COLORFUL", "COLUMBIA", "COMPOUND", "COMPUTER", "CONCLUDE", "CONCRETE", "CONFLICT", "CONSIDER", "CONSTANT", "CONSUMER", "CONTINUE", "CONTRACT", "CONTRAST", "CONVINCE", "CREATION", "CREATIVE", "CRIMINAL", "CRITICAL", "CULTURAL", "CURRENCY", "CUSTOMER", "DATABASE", "DAUGHTER", "DAYLIGHT", "DEADLINE", "DECISION", "DECREASE", "DEFENDER", "DELIVERY", "DEMANDED", "DEPARTED", "DESIGNER", "DIAGNOSIS", "DIALOGUE", "DIAMONDS", "DINOSAUR", "DIRECTOR", "DISASTER", "DISCOUNT", "DISCOVER", "DISEASES", "DISTANCE", "DISTRICT", "DIVIDEND", "DIVISION", "DOCUMENT", "DOMESTIC", "DOMINANT", "DRAMATIC", "EARNINGS", "EASTERN", "ECONOMIC", "EDUCATOR", "ELECTION", "ELEVATOR", "ELIGIBLE", "EMISSION", "EMOTIONS", "EMPLOYEE", "EMPLOYER", "ENDEAVOR", "ENGINEER", "ENORMOUS", "ENTRANCE", "ENVELOPE", "EQUALITY", "EQUATION", "ESTIMATE", "EVALUATE", "EVERYDAY", "EVERYONE", "EVIDENCE", "EXCHANGE", "EXCITING", "EXERCISE", "EXPECTED", "EXPENSES", "EXPOSURE", "EXTERNAL", "FACILITY", "FAMILIAR", "FAVORITE", "FESTIVAL", "FIELDING", "FIFTEEN", "FIGHTING", "FINANCES", "FOOTBALL", "FORECAST", "FOUNTAIN", "FOURTEEN", "FRACTION", "FREEDOM", "FREQUENT", "FRIENDLY", "FUNCTION", "GENERATE", "GOODNESS", "GOVERNOR", "GRADUATE", "GREATEST", "GREETING", "GUARDIAN", "GUIDANCE", "HANDLING", "HARDWARE", "HEADACHE", "HEADINGS", "HERITAGE", "HOSPITAL", "HUMANITY", "HUSBANDS", "IDENTIFY", "IDENTITY", "ILLUSION", "IMAGINE", "IMMUNITY", "IMPERIAL", "INCIDENT", "INCLUDED", "INCLUDES", "INCREASE", "INDUSTRY", "INFECTED", "INFORMAL", "INHERENT", "INNOCENT", "INSTANCE", "INTIMATE", "INVASION", "INVOLVED", "ISOLATED", "JUDGMENT", "KANGAROO", "KEYBOARD", "LANDLORD", "LANGUAGE", "LAUGHTER", "LEARNING", "LITERARY", "LOCATION", "MACARONI", "MAGAZINE", "MAJORITY", "MANAGING", "MATERIAL", "MAXIMIZE", "MEASURED", "MECHANIC", "MEDICINE", "MERCHANT", "MINORITY", "MISTAKES", "MOBILITY", "MONOPOLY", "MONUMENT", "MORTGAGE", "MOVEMENT", "MULTIPLE", "MUSHROOM", "MUSICIAN", "NATIONAL", "NEGATIVE", "NETWORK", "NORTHERN", "NOTEBOOK", "NOWHERE", "OBSERVER", "OBSTACLE", "OCCASION", "OFFENDER", "OFFICIAL", "OPERATOR", "OPPONENT", "OPPOSITE", "ORIGINAL", "OUTBREAK", "OUTCOMES", "OVERSEAS", "PAINTING", "PARALLEL", "PARTNERS", "PASSPORT", "PATIENCE", "PEACEFUL", "PENALTY", "PERCEIVE", "PERFORMS", "PERSONAL", "PHYSICAL", "PICTURES", "PLANNING", "PLATFORM", "PLEASANT", "PLEASURE", "POLITICS", "PORTRAIT", "POSITION", "POSITIVE", "POTATOES", "PRACTICE", "PRECIOUS", "PREDATORY", "PRESENCE", "PRESERVE", "PRESSURE", "PREVIOUS", "PRINCESS", "PRINTER", "PRIORITY", "PROBABLY", "PROCEEDS", "PRODUCER", "PROGRAMS", "PROGRESS", "PROPERTY", "PROPOSAL", "PROPOSED", "PROSPECT", "PROTOCOL", "PROVIDER", "PROVINCE", "PURCHASE", "QUANTITY", "QUARTERS", "QUESTION", "REACTION", "RECEIPTS", "RECEIVED", "RECEIVER", "RECOVERY", "REGIONAL", "REGISTER", "REGISTRY", "REJECTED", "RELATIVE", "RELIABLE", "RELIGION", "REMEMBER", "REPLACED", "REPORTED", "REPORTER", "REPUBLIC", "REQUIRED", "RESEARCH", "RESERVES", "RESIDENT", "RESOURCE", "RESPONSE", "RESTRICT", "REVENUES", "REVISION", "RHYTHMIC", "ROMANTIC", "ROUTINES", "SANDWICH", "SATURDAY", "SCHEDULE", "SCIENTIST", "SCISSORS", "SECURITY", "SEGMENTS", "SELECTED", "SEMINARS", "SENTENCE", "SEPARATE", "SEQUENCE", "SERGEANT", "SERVICES", "SESSIONS", "SEVENTEEN", "SHORTAGE", "SHOULDER", "SICKNESS", "SOFTWARE", "SOLDIERS", "SOLUTION", "SOMEBODY", "SOMETIME", "SOMEWHAT", "SOUTHERN", "SPEAKER", "SPECIFIC", "SPECIMEN", "SPECTRUM", "SPENDING", "SPIRITUAL", "SPONSORS", "STANDARD", "STANDING", "STARTING", "STATION", "STATUE", "STEERING", "STOMACH", "STRANGER", "STRATEGY", "STRENGTH", "STRIKING", "STRUGGLE", "STUDENTS", "STUNNING", "SUBJECTS", "SUBSTANCE", "SURPRISE", "SURVIVAL", "SURVIVOR", "SYLLABLE", "SYMPTOMS", "SYNDROME", "SYNONYM", "TEACHERS", "TEACHING", "TEENAGER", "TENDENCY", "TERRIBLE", "THEATERS", "THEOLOGY", "THEOREMS", "THINKING", "THIRTEEN", "THOROUGH", "THOUGHTS", "THOUSAND", "THREATEN", "THURSDAY", "TOGETHER", "TOMORROW", "TRAINING", "TRANSFER", "TREASURE", "TRIANGLE", "TROPICAL", "TURNOVER", "TWILIGHT", "ULTIMATE", "UMBRELLA", "UNIVERSE", "VACATION", "VALUABLE", "VARIABLE", "VEHICLES", "VERTICAL", "VETERANS", "VICTORIA", "VILLAGER", "VIOLENCE", "VISITORS", "VITAMINS", "VOLCANIC", "VOLUNTEER", "WAITRESS", "WANDERING", "WARDROBE", "WARRANTY", "WARRIORS", "WATCHING", "WATERWAY", "WEAKNESS", "WESTERN", "WHATEVER", "WHENEVER", "WHEREVER", "WILDLIFE", "WINDMILL", "WONDERED", "WOODLAND", "WORKSHOP", "WORLDWIDE", "WRESTLER", "YESTERDAY"];

let content = fs.readFileSync('game.js', 'utf8');

// Replace W9 with W8
content = content.replace(/const W9=\[.*?\];/, `const W8=${JSON.stringify(W8)};`);

// Replace ALL variable
content = content.replace(/const ALL=\[\.\.\.W3,\.\.\.W4,\.\.\.W5,\.\.\.W6,\.\.\.W7\];/, `const ALL=[...W3,...W4,...W5,...W6];`);

// Replace drawFromBag
let oldBag = `shuffleBag=[3,4,4,4,5,5,5,5,6,6,6,7,7];`;
let newBag = `shuffleBag=[3,3,4,4,4,4,5,5,5,5,6,6,6,6];`;
content = content.replace(oldBag, newBag);

// Replace boss checks from 9 to 8
content = content.replace(/forceBoss\s*\?\s*9\s*:/g, `forceBoss ? 8 :`);
content = content.replace(/tl=9;/g, `tl=8;`);
content = content.replace(/tl===9/g, `tl===8`);
content = content.replace(/tl\s*===\s*9/g, `tl===8`);
content = content.replace(/aWord\.length\s*>=\s*9/g, `aWord.length>=8`);
content = content.replace(/aWord\.length\s*<\s*9/g, `aWord.length<8`);
content = content.replace(/aWord\.length\s*!==\s*9/g, `aWord.length!==8`);
content = content.replace(/aWord\.length\s*===\s*9/g, `aWord.length===8`);

// Update wm object
content = content.replace(/const wm=\{3:W3,4:W4,5:W5,6:W6,7:W7,9:W9,10:\['MAPLESTORY'\]\}/g, `const wm={3:W3,4:W4,5:W5,6:W6,8:W8,10:['MAPLESTORY']}`);

fs.writeFileSync('game.js', content);
console.log('done');
